/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.client;

import com.google.gson.*;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gsonfire.GsonFireBuilder;
import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Map;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static final DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static final SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static final OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static final LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static final ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder();
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue        The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.AcceptContract200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.AcceptContract200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Agent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Chart.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Construction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ConstructionMaterial.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Contract.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ContractDeliverGood.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ContractPayment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ContractTerms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Cooldown.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateChart201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateChart201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateShipShipScan201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateShipShipScan201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateShipSystemScan201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateShipSystemScan201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateShipWaypointScan201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateShipWaypointScan201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateSurvey201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.CreateSurvey201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.DeliverContract200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.DeliverContract200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.DeliverContractRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.DockShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ExtractResources201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ExtractResources201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ExtractResourcesRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ExtractResourcesWithSurvey201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ExtractResourcesWithSurvey201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Extraction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ExtractionYield.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Faction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.FactionTrait.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.FulfillContract200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetAgents200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetConstruction200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetContract200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetContracts200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetFaction200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetFactions200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetJumpGate200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetMarket200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetMounts200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetMyAgent200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetMyShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetMyShipCargo200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetMyShips200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetRepairShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetRepairShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetScrapShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetScrapShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetShipCooldown200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetShipModules200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetShipNav200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetShipyard200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200ResponseAnnouncementsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200ResponseLeaderboards.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200ResponseLeaderboardsMostCreditsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200ResponseLeaderboardsMostSubmittedChartsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200ResponseLinksInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200ResponseServerResets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetStatus200ResponseStats.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetSupplyChain200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetSupplyChain200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetSystem200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetSystemWaypoints200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetSystemWaypointsTraitsParameter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetSystems200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.GetWaypoint200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.InstallMount201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.InstallMount201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.InstallMountRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.InstallShipModule201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.InstallShipModule201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.InstallShipModule201ResponseDataTransaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.InstallShipModuleRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Jettison200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Jettison200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.JettisonRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.JumpGate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.JumpShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.JumpShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.JumpShipRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Market.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.MarketTradeGood.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.MarketTransaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Meta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.NavigateShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.NavigateShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.NavigateShipRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.NegotiateContract200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.NegotiateContract200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.OrbitShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.OrbitShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PatchShipNav200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PatchShipNav200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PatchShipNavRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PurchaseCargo201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PurchaseCargoRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PurchaseShip201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PurchaseShip201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.PurchaseShipRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RefuelShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RefuelShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RefuelShipRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Register201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Register201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RegisterRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RemoveModule201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RemoveMount201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RemoveMount201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RemoveMountRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RemoveShipModuleRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RepairShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RepairShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.RepairTransaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScannedShip.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScannedShipEngine.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScannedShipFrame.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScannedShipMountsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScannedShipReactor.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScannedSystem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScannedWaypoint.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScrapShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScrapShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ScrapTransaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SellCargo201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SellCargo201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SellCargoRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Ship.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipCargo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipCargoItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipConditionEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipCrew.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipEngine.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipFrame.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipFuel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipFuelConsumed.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipModificationTransaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipModule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipMount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipNav.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipNavRoute.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipNavRouteWaypoint.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipReactor.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipRefine201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipRefine201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipRefine201ResponseDataProducedInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipRefineRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipRegistration.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipRequirements.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Shipyard.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipyardShip.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipyardShipCrew.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipyardShipTypesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.ShipyardTransaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Siphon.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SiphonResources201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SiphonResources201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SiphonYield.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SupplyConstruction201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SupplyConstruction201ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SupplyConstructionRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Survey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SurveyDeposit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.System.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SystemFaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.SystemWaypoint.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.TradeGood.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.TransferCargo200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.TransferCargoRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.WarpShip200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.WarpShip200ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.Waypoint.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.WaypointFaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.WaypointModifier.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.WaypointOrbital.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new xyz.faria.space.spaceapi.model.WaypointTrait.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Deserialize the given JSON InputStream to a Java object.
     *
     * @param <T>         Type
     * @param inputStream The JSON InputStream
     * @param returnType  The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
            if (isLenientOnJson) {
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                JsonReader jsonReader = new JsonReader(reader);
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length() - 5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {
        }

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {
        }

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
