vaadin.launch-browser=true
spring.application.name=space
spring.datasource.url=jdbc:postgresql://192.168.1.230:5437/spacegame
spring.datasource.username=space
spring.datasource.password=traders
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.liquibase.drop-first=false
sentry.dsn=https://36abcf28cfec77bdb31449745ef574c8@sentry.faria.xyz/4
sentry.send-default-pii=true
sentry.logs.enabled=true
sentry.traces-sample-rate=0.1