vaadin.launch-browser=true
spring.application.name=space
spring.datasource.url=jdbc:postgresql://localhost:5437/spacegame
spring.datasource.username=space
spring.datasource.password=traders
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.drop-first=false
