/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * The details of the required construction materials for a given waypoint under construction.
 */

public class ConstructionMaterial {
    public static final String SERIALIZED_NAME_TRADE_SYMBOL = "tradeSymbol";
    @SerializedName(SERIALIZED_NAME_TRADE_SYMBOL)
    @javax.annotation.Nonnull
    private TradeSymbol tradeSymbol;

    public static final String SERIALIZED_NAME_REQUIRED = "required";
    @SerializedName(SERIALIZED_NAME_REQUIRED)
    @javax.annotation.Nonnull
    private Integer required;

    public static final String SERIALIZED_NAME_FULFILLED = "fulfilled";
    @SerializedName(SERIALIZED_NAME_FULFILLED)
    @javax.annotation.Nonnull
    private Integer fulfilled;

    public ConstructionMaterial() {
    }

    public ConstructionMaterial tradeSymbol(@javax.annotation.Nonnull TradeSymbol tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
        return this;
    }

    /**
     * Get tradeSymbol
     *
     * @return tradeSymbol
     */
    @javax.annotation.Nonnull
    public TradeSymbol getTradeSymbol() {
        return tradeSymbol;
    }

    public void setTradeSymbol(@javax.annotation.Nonnull TradeSymbol tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
    }


    public ConstructionMaterial required(@javax.annotation.Nonnull Integer required) {
        this.required = required;
        return this;
    }

    /**
     * The number of units required.
     *
     * @return required
     */
    @javax.annotation.Nonnull
    public Integer getRequired() {
        return required;
    }

    public void setRequired(@javax.annotation.Nonnull Integer required) {
        this.required = required;
    }


    public ConstructionMaterial fulfilled(@javax.annotation.Nonnull Integer fulfilled) {
        this.fulfilled = fulfilled;
        return this;
    }

    /**
     * The number of units fulfilled toward the required amount.
     *
     * @return fulfilled
     */
    @javax.annotation.Nonnull
    public Integer getFulfilled() {
        return fulfilled;
    }

    public void setFulfilled(@javax.annotation.Nonnull Integer fulfilled) {
        this.fulfilled = fulfilled;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConstructionMaterial constructionMaterial = (ConstructionMaterial) o;
        return Objects.equals(this.tradeSymbol, constructionMaterial.tradeSymbol) &&
                Objects.equals(this.required, constructionMaterial.required) &&
                Objects.equals(this.fulfilled, constructionMaterial.fulfilled);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tradeSymbol, required, fulfilled);
    }

    @Override
    public String toString() {
        String sb = "class ConstructionMaterial {\n" +
                "    tradeSymbol: " + toIndentedString(tradeSymbol) + "\n" +
                "    required: " + toIndentedString(required) + "\n" +
                "    fulfilled: " + toIndentedString(fulfilled) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("tradeSymbol", "required", "fulfilled"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("tradeSymbol", "required", "fulfilled"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ConstructionMaterial
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ConstructionMaterial.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ConstructionMaterial is not found in the empty JSON string", ConstructionMaterial.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ConstructionMaterial.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConstructionMaterial` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ConstructionMaterial.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `tradeSymbol`
        TradeSymbol.validateJsonElement(jsonObj.get("tradeSymbol"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ConstructionMaterial.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ConstructionMaterial' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ConstructionMaterial> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(ConstructionMaterial.class));

            return (TypeAdapter<T>) new TypeAdapter<ConstructionMaterial>() {
                @Override
                public void write(JsonWriter out, ConstructionMaterial value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ConstructionMaterial read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ConstructionMaterial given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ConstructionMaterial
     * @throws IOException if the JSON string is invalid with respect to ConstructionMaterial
     */
    public static ConstructionMaterial fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ConstructionMaterial.class);
    }

    /**
     * Convert an instance of ConstructionMaterial to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

