/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * DeliverContract200ResponseData
 */

public class DeliverContract200ResponseData {

    public static final String SERIALIZED_NAME_CONTRACT = "contract";
    @SerializedName(SERIALIZED_NAME_CONTRACT)
    @javax.annotation.Nonnull
    private Contract contract;

    public static final String SERIALIZED_NAME_CARGO = "cargo";
    @SerializedName(SERIALIZED_NAME_CARGO)
    @javax.annotation.Nonnull
    private ShipCargo cargo;

    public DeliverContract200ResponseData() {
    }

    public DeliverContract200ResponseData contract(@javax.annotation.Nonnull Contract contract) {
        this.contract = contract;
        return this;
    }

    /**
     * Get contract
     *
     * @return contract
     */
    @javax.annotation.Nonnull
    public Contract getContract() {
        return contract;
    }

    public void setContract(@javax.annotation.Nonnull Contract contract) {
        this.contract = contract;
    }


    public DeliverContract200ResponseData cargo(@javax.annotation.Nonnull ShipCargo cargo) {
        this.cargo = cargo;
        return this;
    }

    /**
     * Get cargo
     *
     * @return cargo
     */
    @javax.annotation.Nonnull
    public ShipCargo getCargo() {
        return cargo;
    }

    public void setCargo(@javax.annotation.Nonnull ShipCargo cargo) {
        this.cargo = cargo;
    }


    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *                     DeliverContract200ResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DeliverContract200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in DeliverContract200ResponseData is not found in the empty JSON string",
                    DeliverContract200ResponseData.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!DeliverContract200ResponseData.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `DeliverContract200ResponseData` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : DeliverContract200ResponseData.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s",
                    requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `contract`
        Contract.validateJsonElement(jsonObj.get("contract"));
        // validate the required field `cargo`
        ShipCargo.validateJsonElement(jsonObj.get("cargo"));
    }

    @Override
    public int hashCode() {
        return Objects.hash(contract, cargo);
    }

    /**
     * Create an instance of DeliverContract200ResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DeliverContract200ResponseData
     * @throws IOException if the JSON string is invalid with respect to
     *                     DeliverContract200ResponseData
     */
    public static DeliverContract200ResponseData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DeliverContract200ResponseData.class);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeliverContract200ResponseData deliverContract200ResponseData = (DeliverContract200ResponseData) o;
        return Objects.equals(this.contract, deliverContract200ResponseData.contract) &&
            Objects.equals(this.cargo, deliverContract200ResponseData.cargo);
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("contract", "cargo"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("contract", "cargo"));
    }

    @Override
    public String toString() {
        String sb = "class DeliverContract200ResponseData {\n" +
            "    contract: " + toIndentedString(contract) + "\n" +
            "    cargo: " + toIndentedString(cargo) + "\n" +
            "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DeliverContract200ResponseData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DeliverContract200ResponseData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DeliverContract200ResponseData> thisAdapter
                = gson.getDelegateAdapter(this,
                TypeToken.get(DeliverContract200ResponseData.class));

            return (TypeAdapter<T>) new TypeAdapter<DeliverContract200ResponseData>() {
                @Override
                public void write(JsonWriter out, DeliverContract200ResponseData value)
                    throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public DeliverContract200ResponseData read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Convert an instance of DeliverContract200ResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

