/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * DeliverContractRequest
 */

public class DeliverContractRequest {

    public static final String SERIALIZED_NAME_SHIP_SYMBOL = "shipSymbol";
    @SerializedName(SERIALIZED_NAME_SHIP_SYMBOL)
    @javax.annotation.Nonnull
    private String shipSymbol;

    public static final String SERIALIZED_NAME_TRADE_SYMBOL = "tradeSymbol";
    @SerializedName(SERIALIZED_NAME_TRADE_SYMBOL)
    @javax.annotation.Nonnull
    private String tradeSymbol;

    public static final String SERIALIZED_NAME_UNITS = "units";
    @SerializedName(SERIALIZED_NAME_UNITS)
    @javax.annotation.Nonnull
    private Integer units;

    public DeliverContractRequest() {
    }

    public DeliverContractRequest shipSymbol(@javax.annotation.Nonnull String shipSymbol) {
        this.shipSymbol = shipSymbol;
        return this;
    }

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("shipSymbol", "tradeSymbol", "units"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(
            Arrays.asList("shipSymbol", "tradeSymbol", "units"));
    }

    public void setShipSymbol(@javax.annotation.Nonnull String shipSymbol) {
        this.shipSymbol = shipSymbol;
    }


    public DeliverContractRequest tradeSymbol(@javax.annotation.Nonnull String tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
        return this;
    }

    /**
     * The symbol of the good to deliver.
     *
     * @return tradeSymbol
     */
    @javax.annotation.Nonnull
    public String getTradeSymbol() {
        return tradeSymbol;
    }

    public void setTradeSymbol(@javax.annotation.Nonnull String tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
    }


    public DeliverContractRequest units(@javax.annotation.Nonnull Integer units) {
        this.units = units;
        return this;
    }

    /**
     * Amount of units to deliver.
     *
     * @return units
     */
    @javax.annotation.Nonnull
    public Integer getUnits() {
        return units;
    }

    public void setUnits(@javax.annotation.Nonnull Integer units) {
        this.units = units;
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DeliverContractRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DeliverContractRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in DeliverContractRequest is not found in the empty JSON string",
                    DeliverContractRequest.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!DeliverContractRequest.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `DeliverContractRequest` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : DeliverContractRequest.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s", requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("shipSymbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `shipSymbol` to be a primitive type in the JSON string but got `%s`",
                jsonObj.get("shipSymbol").toString()));
        }
        if (!jsonObj.get("tradeSymbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `tradeSymbol` to be a primitive type in the JSON string but got `%s`",
                jsonObj.get("tradeSymbol").toString()));
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(shipSymbol, tradeSymbol, units);
    }

    /**
     * Symbol of a ship located in the destination to deliver a contract and that has a good to
     * deliver in its cargo.
     *
     * @return shipSymbol
     */
    @javax.annotation.Nonnull
    public String getShipSymbol() {
        return shipSymbol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeliverContractRequest deliverContractRequest = (DeliverContractRequest) o;
        return Objects.equals(this.shipSymbol, deliverContractRequest.shipSymbol) &&
            Objects.equals(this.tradeSymbol, deliverContractRequest.tradeSymbol) &&
            Objects.equals(this.units, deliverContractRequest.units);
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    @Override
    public String toString() {
        String sb = "class DeliverContractRequest {\n" +
            "    shipSymbol: " + toIndentedString(shipSymbol) + "\n" +
            "    tradeSymbol: " + toIndentedString(tradeSymbol) + "\n" +
            "    units: " + toIndentedString(units) + "\n" +
            "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DeliverContractRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DeliverContractRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DeliverContractRequest> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(DeliverContractRequest.class));

            return (TypeAdapter<T>) new TypeAdapter<DeliverContractRequest>() {
                @Override
                public void write(JsonWriter out, DeliverContractRequest value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public DeliverContractRequest read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of DeliverContractRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DeliverContractRequest
     * @throws IOException if the JSON string is invalid with respect to DeliverContractRequest
     */
    public static DeliverContractRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DeliverContractRequest.class);
    }

    /**
     * Convert an instance of DeliverContractRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

