/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * GetStatus200ResponseAnnouncementsInner
 */

public class GetStatus200ResponseAnnouncementsInner {

    public static final String SERIALIZED_NAME_TITLE = "title";
    @SerializedName(SERIALIZED_NAME_TITLE)
    @javax.annotation.Nonnull
    private String title;

    public static final String SERIALIZED_NAME_BODY = "body";
    @SerializedName(SERIALIZED_NAME_BODY)
    @javax.annotation.Nonnull
    private String body;

    public GetStatus200ResponseAnnouncementsInner() {
    }

    public GetStatus200ResponseAnnouncementsInner title(@javax.annotation.Nonnull String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     */
    @javax.annotation.Nonnull
    public String getTitle() {
        return title;
    }

    public void setTitle(@javax.annotation.Nonnull String title) {
        this.title = title;
    }


    public GetStatus200ResponseAnnouncementsInner body(@javax.annotation.Nonnull String body) {
        this.body = body;
        return this;
    }

    /**
     * Get body
     *
     * @return body
     */
    @javax.annotation.Nonnull
    public String getBody() {
        return body;
    }

    public void setBody(@javax.annotation.Nonnull String body) {
        this.body = body;
    }


    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *                     GetStatus200ResponseAnnouncementsInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetStatus200ResponseAnnouncementsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in GetStatus200ResponseAnnouncementsInner is not found in the empty JSON string",
                    GetStatus200ResponseAnnouncementsInner.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetStatus200ResponseAnnouncementsInner.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `GetStatus200ResponseAnnouncementsInner` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : GetStatus200ResponseAnnouncementsInner.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s",
                    requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("title").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `title` to be a primitive type in the JSON string but got `%s`",
                jsonObj.get("title").toString()));
        }
        if (!jsonObj.get("body").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `body` to be a primitive type in the JSON string but got `%s`",
                jsonObj.get("body").toString()));
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(title, body);
    }

    /**
     * Create an instance of GetStatus200ResponseAnnouncementsInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetStatus200ResponseAnnouncementsInner
     * @throws IOException if the JSON string is invalid with respect to
     *                     GetStatus200ResponseAnnouncementsInner
     */
    public static GetStatus200ResponseAnnouncementsInner fromJson(String jsonString)
        throws IOException {
        return JSON.getGson().fromJson(jsonString, GetStatus200ResponseAnnouncementsInner.class);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetStatus200ResponseAnnouncementsInner getStatus200ResponseAnnouncementsInner = (GetStatus200ResponseAnnouncementsInner) o;
        return Objects.equals(this.title, getStatus200ResponseAnnouncementsInner.title) &&
            Objects.equals(this.body, getStatus200ResponseAnnouncementsInner.body);
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("title", "body"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("title", "body"));
    }

    @Override
    public String toString() {
        String sb = "class GetStatus200ResponseAnnouncementsInner {\n" +
            "    title: " + toIndentedString(title) + "\n" +
            "    body: " + toIndentedString(body) + "\n" +
            "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetStatus200ResponseAnnouncementsInner.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetStatus200ResponseAnnouncementsInner' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetStatus200ResponseAnnouncementsInner> thisAdapter
                = gson.getDelegateAdapter(this,
                TypeToken.get(GetStatus200ResponseAnnouncementsInner.class));

            return (TypeAdapter<T>) new TypeAdapter<GetStatus200ResponseAnnouncementsInner>() {
                @Override
                public void write(JsonWriter out, GetStatus200ResponseAnnouncementsInner value)
                    throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetStatus200ResponseAnnouncementsInner read(JsonReader in)
                    throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Convert an instance of GetStatus200ResponseAnnouncementsInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

