/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * GetStatus200ResponseStats
 */

public class GetStatus200ResponseStats {
    public static final String SERIALIZED_NAME_ACCOUNTS = "accounts";
    @SerializedName(SERIALIZED_NAME_ACCOUNTS)
    @javax.annotation.Nullable
    private Integer accounts;

    public static final String SERIALIZED_NAME_AGENTS = "agents";
    @SerializedName(SERIALIZED_NAME_AGENTS)
    @javax.annotation.Nonnull
    private Integer agents;

    public static final String SERIALIZED_NAME_SHIPS = "ships";
    @SerializedName(SERIALIZED_NAME_SHIPS)
    @javax.annotation.Nonnull
    private Integer ships;

    public static final String SERIALIZED_NAME_SYSTEMS = "systems";
    @SerializedName(SERIALIZED_NAME_SYSTEMS)
    @javax.annotation.Nonnull
    private Integer systems;

    public static final String SERIALIZED_NAME_WAYPOINTS = "waypoints";
    @SerializedName(SERIALIZED_NAME_WAYPOINTS)
    @javax.annotation.Nonnull
    private Integer waypoints;

    public GetStatus200ResponseStats() {
    }

    public GetStatus200ResponseStats accounts(@javax.annotation.Nullable Integer accounts) {
        this.accounts = accounts;
        return this;
    }

    /**
     * Total number of accounts registered on the game server.
     *
     * @return accounts
     */
    @javax.annotation.Nullable
    public Integer getAccounts() {
        return accounts;
    }

    public void setAccounts(@javax.annotation.Nullable Integer accounts) {
        this.accounts = accounts;
    }


    public GetStatus200ResponseStats agents(@javax.annotation.Nonnull Integer agents) {
        this.agents = agents;
        return this;
    }

    /**
     * Number of registered agents in the game.
     *
     * @return agents
     */
    @javax.annotation.Nonnull
    public Integer getAgents() {
        return agents;
    }

    public void setAgents(@javax.annotation.Nonnull Integer agents) {
        this.agents = agents;
    }


    public GetStatus200ResponseStats ships(@javax.annotation.Nonnull Integer ships) {
        this.ships = ships;
        return this;
    }

    /**
     * Total number of ships in the game.
     *
     * @return ships
     */
    @javax.annotation.Nonnull
    public Integer getShips() {
        return ships;
    }

    public void setShips(@javax.annotation.Nonnull Integer ships) {
        this.ships = ships;
    }


    public GetStatus200ResponseStats systems(@javax.annotation.Nonnull Integer systems) {
        this.systems = systems;
        return this;
    }

    /**
     * Total number of systems in the game.
     *
     * @return systems
     */
    @javax.annotation.Nonnull
    public Integer getSystems() {
        return systems;
    }

    public void setSystems(@javax.annotation.Nonnull Integer systems) {
        this.systems = systems;
    }


    public GetStatus200ResponseStats waypoints(@javax.annotation.Nonnull Integer waypoints) {
        this.waypoints = waypoints;
        return this;
    }

    /**
     * Total number of waypoints in the game.
     *
     * @return waypoints
     */
    @javax.annotation.Nonnull
    public Integer getWaypoints() {
        return waypoints;
    }

    public void setWaypoints(@javax.annotation.Nonnull Integer waypoints) {
        this.waypoints = waypoints;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetStatus200ResponseStats getStatus200ResponseStats = (GetStatus200ResponseStats) o;
        return Objects.equals(this.accounts, getStatus200ResponseStats.accounts) &&
                Objects.equals(this.agents, getStatus200ResponseStats.agents) &&
                Objects.equals(this.ships, getStatus200ResponseStats.ships) &&
                Objects.equals(this.systems, getStatus200ResponseStats.systems) &&
                Objects.equals(this.waypoints, getStatus200ResponseStats.waypoints);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accounts, agents, ships, systems, waypoints);
    }

    @Override
    public String toString() {
        String sb = "class GetStatus200ResponseStats {\n" +
                "    accounts: " + toIndentedString(accounts) + "\n" +
                "    agents: " + toIndentedString(agents) + "\n" +
                "    ships: " + toIndentedString(ships) + "\n" +
                "    systems: " + toIndentedString(systems) + "\n" +
                "    waypoints: " + toIndentedString(waypoints) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("accounts", "agents", "ships", "systems", "waypoints"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("agents", "ships", "systems", "waypoints"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetStatus200ResponseStats
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetStatus200ResponseStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetStatus200ResponseStats is not found in the empty JSON string", GetStatus200ResponseStats.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetStatus200ResponseStats.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetStatus200ResponseStats` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : GetStatus200ResponseStats.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetStatus200ResponseStats.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetStatus200ResponseStats' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetStatus200ResponseStats> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(GetStatus200ResponseStats.class));

            return (TypeAdapter<T>) new TypeAdapter<GetStatus200ResponseStats>() {
                @Override
                public void write(JsonWriter out, GetStatus200ResponseStats value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetStatus200ResponseStats read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of GetStatus200ResponseStats given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetStatus200ResponseStats
     * @throws IOException if the JSON string is invalid with respect to GetStatus200ResponseStats
     */
    public static GetStatus200ResponseStats fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetStatus200ResponseStats.class);
    }

    /**
     * Convert an instance of GetStatus200ResponseStats to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

