/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 *
 */

public class GetSystemWaypoints200Response {
    public static final String SERIALIZED_NAME_DATA = "data";
    @SerializedName(SERIALIZED_NAME_DATA)
    @javax.annotation.Nonnull
    private List<Waypoint> data = new ArrayList<>();

    public static final String SERIALIZED_NAME_META = "meta";
    @SerializedName(SERIALIZED_NAME_META)
    @javax.annotation.Nonnull
    private Meta meta;

    public GetSystemWaypoints200Response() {
    }

    public GetSystemWaypoints200Response data(@javax.annotation.Nonnull List<Waypoint> data) {
        this.data = data;
        return this;
    }

    public GetSystemWaypoints200Response addDataItem(Waypoint dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Get data
     *
     * @return data
     */
    @javax.annotation.Nonnull
    public List<Waypoint> getData() {
        return data;
    }

    public void setData(@javax.annotation.Nonnull List<Waypoint> data) {
        this.data = data;
    }


    public GetSystemWaypoints200Response meta(@javax.annotation.Nonnull Meta meta) {
        this.meta = meta;
        return this;
    }

    /**
     * Get meta
     *
     * @return meta
     */
    @javax.annotation.Nonnull
    public Meta getMeta() {
        return meta;
    }

    public void setMeta(@javax.annotation.Nonnull Meta meta) {
        this.meta = meta;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSystemWaypoints200Response getSystemWaypoints200Response = (GetSystemWaypoints200Response) o;
        return Objects.equals(this.data, getSystemWaypoints200Response.data) &&
                Objects.equals(this.meta, getSystemWaypoints200Response.meta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, meta);
    }

    @Override
    public String toString() {
        String sb = "class GetSystemWaypoints200Response {\n" +
                "    data: " + toIndentedString(data) + "\n" +
                "    meta: " + toIndentedString(meta) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("data", "meta"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("data", "meta"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetSystemWaypoints200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetSystemWaypoints200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetSystemWaypoints200Response is not found in the empty JSON string", GetSystemWaypoints200Response.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetSystemWaypoints200Response.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetSystemWaypoints200Response` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : GetSystemWaypoints200Response.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // ensure the json data is an array
        if (!jsonObj.get("data").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `data` to be an array in the JSON string but got `%s`", jsonObj.get("data").toString()));
        }

        JsonArray jsonArraydata = jsonObj.getAsJsonArray("data");
        // validate the required field `data` (array)
        for (int i = 0; i < jsonArraydata.size(); i++) {
            Waypoint.validateJsonElement(jsonArraydata.get(i));
        }
        // validate the required field `meta`
        Meta.validateJsonElement(jsonObj.get("meta"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetSystemWaypoints200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetSystemWaypoints200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetSystemWaypoints200Response> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(GetSystemWaypoints200Response.class));

            return (TypeAdapter<T>) new TypeAdapter<GetSystemWaypoints200Response>() {
                @Override
                public void write(JsonWriter out, GetSystemWaypoints200Response value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GetSystemWaypoints200Response read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of GetSystemWaypoints200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetSystemWaypoints200Response
     * @throws IOException if the JSON string is invalid with respect to GetSystemWaypoints200Response
     */
    public static GetSystemWaypoints200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetSystemWaypoints200Response.class);
    }

    /**
     * Convert an instance of GetSystemWaypoints200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

