/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * InstallMount201ResponseData
 */

public class InstallMount201ResponseData {

    public static final String SERIALIZED_NAME_AGENT = "agent";
    @SerializedName(SERIALIZED_NAME_AGENT)
    @javax.annotation.Nonnull
    private Agent agent;

    public static final String SERIALIZED_NAME_MOUNTS = "mounts";
    @SerializedName(SERIALIZED_NAME_MOUNTS)
    @javax.annotation.Nonnull
    private List<ShipMount> mounts = new ArrayList<>();

    public static final String SERIALIZED_NAME_CARGO = "cargo";
    @SerializedName(SERIALIZED_NAME_CARGO)
    @javax.annotation.Nonnull
    private ShipCargo cargo;

    public static final String SERIALIZED_NAME_TRANSACTION = "transaction";
    @SerializedName(SERIALIZED_NAME_TRANSACTION)
    @javax.annotation.Nonnull
    private ShipModificationTransaction transaction;

    public InstallMount201ResponseData() {
    }

    public InstallMount201ResponseData agent(@javax.annotation.Nonnull Agent agent) {
        this.agent = agent;
        return this;
    }

    /**
     * Get agent
     *
     * @return agent
     */
    @javax.annotation.Nonnull
    public Agent getAgent() {
        return agent;
    }

    public void setAgent(@javax.annotation.Nonnull Agent agent) {
        this.agent = agent;
    }


    public InstallMount201ResponseData mounts(@javax.annotation.Nonnull List<ShipMount> mounts) {
        this.mounts = mounts;
        return this;
    }

    public InstallMount201ResponseData addMountsItem(ShipMount mountsItem) {
        if (this.mounts == null) {
            this.mounts = new ArrayList<>();
        }
        this.mounts.add(mountsItem);
        return this;
    }

    /**
     * List of installed mounts after the installation of the new mount.
     *
     * @return mounts
     */
    @javax.annotation.Nonnull
    public List<ShipMount> getMounts() {
        return mounts;
    }

    public void setMounts(@javax.annotation.Nonnull List<ShipMount> mounts) {
        this.mounts = mounts;
    }


    public InstallMount201ResponseData cargo(@javax.annotation.Nonnull ShipCargo cargo) {
        this.cargo = cargo;
        return this;
    }

    /**
     * Get cargo
     *
     * @return cargo
     */
    @javax.annotation.Nonnull
    public ShipCargo getCargo() {
        return cargo;
    }

    public void setCargo(@javax.annotation.Nonnull ShipCargo cargo) {
        this.cargo = cargo;
    }


    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(
            Arrays.asList("agent", "mounts", "cargo", "transaction"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(
            Arrays.asList("agent", "mounts", "cargo", "transaction"));
    }

    /**
     * Get transaction
     *
     * @return transaction
     */
    @javax.annotation.Nonnull
    public ShipModificationTransaction getTransaction() {
        return transaction;
    }

    public void setTransaction(@javax.annotation.Nonnull ShipModificationTransaction transaction) {
        this.transaction = transaction;
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *                     InstallMount201ResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!InstallMount201ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in InstallMount201ResponseData is not found in the empty JSON string",
                    InstallMount201ResponseData.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!InstallMount201ResponseData.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `InstallMount201ResponseData` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : InstallMount201ResponseData.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s",
                    requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `agent`
        Agent.validateJsonElement(jsonObj.get("agent"));
        // ensure the json data is an array
        if (!jsonObj.get("mounts").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `mounts` to be an array in the JSON string but got `%s`",
                jsonObj.get("mounts").toString()));
        }

        JsonArray jsonArraymounts = jsonObj.getAsJsonArray("mounts");
        // validate the required field `mounts` (array)
        for (int i = 0; i < jsonArraymounts.size(); i++) {
            ShipMount.validateJsonElement(jsonArraymounts.get(i));
        }
        // validate the required field `cargo`
        ShipCargo.validateJsonElement(jsonObj.get("cargo"));
        // validate the required field `transaction`
        ShipModificationTransaction.validateJsonElement(jsonObj.get("transaction"));
    }

    @Override
    public int hashCode() {
        return Objects.hash(agent, mounts, cargo, transaction);
    }

    /**
     * Create an instance of InstallMount201ResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of InstallMount201ResponseData
     * @throws IOException if the JSON string is invalid with respect to
     *                     InstallMount201ResponseData
     */
    public static InstallMount201ResponseData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, InstallMount201ResponseData.class);
    }

    public InstallMount201ResponseData transaction(
        @javax.annotation.Nonnull ShipModificationTransaction transaction) {
        this.transaction = transaction;
        return this;
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InstallMount201ResponseData installMount201ResponseData = (InstallMount201ResponseData) o;
        return Objects.equals(this.agent, installMount201ResponseData.agent) &&
            Objects.equals(this.mounts, installMount201ResponseData.mounts) &&
            Objects.equals(this.cargo, installMount201ResponseData.cargo) &&
            Objects.equals(this.transaction, installMount201ResponseData.transaction);
    }

    @Override
    public String toString() {
        String sb = "class InstallMount201ResponseData {\n" +
            "    agent: " + toIndentedString(agent) + "\n" +
            "    mounts: " + toIndentedString(mounts) + "\n" +
            "    cargo: " + toIndentedString(cargo) + "\n" +
            "    transaction: " + toIndentedString(transaction) + "\n" +
            "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!InstallMount201ResponseData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'InstallMount201ResponseData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<InstallMount201ResponseData> thisAdapter
                = gson.getDelegateAdapter(this,
                TypeToken.get(InstallMount201ResponseData.class));

            return (TypeAdapter<T>) new TypeAdapter<InstallMount201ResponseData>() {
                @Override
                public void write(JsonWriter out, InstallMount201ResponseData value)
                    throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public InstallMount201ResponseData read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Convert an instance of InstallMount201ResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

