/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * JumpShipRequest
 */

public class JumpShipRequest {
    public static final String SERIALIZED_NAME_WAYPOINT_SYMBOL = "waypointSymbol";
    @SerializedName(SERIALIZED_NAME_WAYPOINT_SYMBOL)
    @javax.annotation.Nonnull
    private String waypointSymbol;

    public JumpShipRequest() {
    }

    public JumpShipRequest waypointSymbol(@javax.annotation.Nonnull String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
        return this;
    }

    /**
     * The symbol of the waypoint to jump to. The destination must be a connected waypoint.
     *
     * @return waypointSymbol
     */
    @javax.annotation.Nonnull
    public String getWaypointSymbol() {
        return waypointSymbol;
    }

    public void setWaypointSymbol(@javax.annotation.Nonnull String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JumpShipRequest jumpShipRequest = (JumpShipRequest) o;
        return Objects.equals(this.waypointSymbol, jumpShipRequest.waypointSymbol);
    }

    @Override
    public int hashCode() {
        return Objects.hash(waypointSymbol);
    }

    @Override
    public String toString() {
        String sb = "class JumpShipRequest {\n" +
                "    waypointSymbol: " + toIndentedString(waypointSymbol) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(List.of("waypointSymbol"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(List.of("waypointSymbol"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to JumpShipRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!JumpShipRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in JumpShipRequest is not found in the empty JSON string", JumpShipRequest.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!JumpShipRequest.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `JumpShipRequest` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : JumpShipRequest.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("waypointSymbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `waypointSymbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("waypointSymbol").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!JumpShipRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'JumpShipRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<JumpShipRequest> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(JumpShipRequest.class));

            return (TypeAdapter<T>) new TypeAdapter<JumpShipRequest>() {
                @Override
                public void write(JsonWriter out, JumpShipRequest value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public JumpShipRequest read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of JumpShipRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of JumpShipRequest
     * @throws IOException if the JSON string is invalid with respect to JumpShipRequest
     */
    public static JumpShipRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, JumpShipRequest.class);
    }

    /**
     * Convert an instance of JumpShipRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

