/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * Market details.
 */

public class Market {

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";
    @SerializedName(SERIALIZED_NAME_SYMBOL)
    @javax.annotation.Nonnull
    private String symbol;

    public static final String SERIALIZED_NAME_EXPORTS = "exports";
    @SerializedName(SERIALIZED_NAME_EXPORTS)
    @javax.annotation.Nonnull
    private List<TradeGood> exports = new ArrayList<>();

    public static final String SERIALIZED_NAME_IMPORTS = "imports";
    @SerializedName(SERIALIZED_NAME_IMPORTS)
    @javax.annotation.Nonnull
    private List<TradeGood> imports = new ArrayList<>();

    public static final String SERIALIZED_NAME_EXCHANGE = "exchange";
    @SerializedName(SERIALIZED_NAME_EXCHANGE)
    @javax.annotation.Nonnull
    private List<TradeGood> exchange = new ArrayList<>();

    public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
    @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
    @javax.annotation.Nullable
    private List<MarketTransaction> transactions = new ArrayList<>();

    public static final String SERIALIZED_NAME_TRADE_GOODS = "tradeGoods";
    @SerializedName(SERIALIZED_NAME_TRADE_GOODS)
    @javax.annotation.Nullable
    private List<MarketTradeGood> tradeGoods = new ArrayList<>();

    public Market() {
    }

    public Market symbol(@javax.annotation.Nonnull String symbol) {
        this.symbol = symbol;
        return this;
    }

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(
            Arrays.asList("symbol", "exports", "imports", "exchange", "transactions",
                "tradeGoods"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(
            Arrays.asList("symbol", "exports", "imports", "exchange"));
    }

    public void setSymbol(@javax.annotation.Nonnull String symbol) {
        this.symbol = symbol;
    }


    public Market exports(@javax.annotation.Nonnull List<TradeGood> exports) {
        this.exports = exports;
        return this;
    }

    public Market addExportsItem(TradeGood exportsItem) {
        if (this.exports == null) {
            this.exports = new ArrayList<>();
        }
        this.exports.add(exportsItem);
        return this;
    }

    /**
     * The list of goods that are exported from this market.
     *
     * @return exports
     */
    @javax.annotation.Nonnull
    public List<TradeGood> getExports() {
        return exports;
    }

    public void setExports(@javax.annotation.Nonnull List<TradeGood> exports) {
        this.exports = exports;
    }


    public Market imports(@javax.annotation.Nonnull List<TradeGood> imports) {
        this.imports = imports;
        return this;
    }

    public Market addImportsItem(TradeGood importsItem) {
        if (this.imports == null) {
            this.imports = new ArrayList<>();
        }
        this.imports.add(importsItem);
        return this;
    }

    /**
     * The list of goods that are sought as imports in this market.
     *
     * @return imports
     */
    @javax.annotation.Nonnull
    public List<TradeGood> getImports() {
        return imports;
    }

    public void setImports(@javax.annotation.Nonnull List<TradeGood> imports) {
        this.imports = imports;
    }


    public Market exchange(@javax.annotation.Nonnull List<TradeGood> exchange) {
        this.exchange = exchange;
        return this;
    }

    public Market addExchangeItem(TradeGood exchangeItem) {
        if (this.exchange == null) {
            this.exchange = new ArrayList<>();
        }
        this.exchange.add(exchangeItem);
        return this;
    }

    /**
     * The list of goods that are bought and sold between agents at this market.
     *
     * @return exchange
     */
    @javax.annotation.Nonnull
    public List<TradeGood> getExchange() {
        return exchange;
    }

    public void setExchange(@javax.annotation.Nonnull List<TradeGood> exchange) {
        this.exchange = exchange;
    }


    public Market transactions(@javax.annotation.Nullable List<MarketTransaction> transactions) {
        this.transactions = transactions;
        return this;
    }

    public Market addTransactionsItem(MarketTransaction transactionsItem) {
        if (this.transactions == null) {
            this.transactions = new ArrayList<>();
        }
        this.transactions.add(transactionsItem);
        return this;
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to Market
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!Market.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in Market is not found in the empty JSON string",
                    Market.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!Market.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `Market` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : Market.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s", requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("symbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`",
                jsonObj.get("symbol").toString()));
        }
        // ensure the json data is an array
        if (!jsonObj.get("exports").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `exports` to be an array in the JSON string but got `%s`",
                jsonObj.get("exports").toString()));
        }

        JsonArray jsonArrayexports = jsonObj.getAsJsonArray("exports");
        // validate the required field `exports` (array)
        for (int i = 0; i < jsonArrayexports.size(); i++) {
            TradeGood.validateJsonElement(jsonArrayexports.get(i));
        }
        // ensure the json data is an array
        if (!jsonObj.get("imports").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `imports` to be an array in the JSON string but got `%s`",
                jsonObj.get("imports").toString()));
        }

        JsonArray jsonArrayimports = jsonObj.getAsJsonArray("imports");
        // validate the required field `imports` (array)
        for (int i = 0; i < jsonArrayimports.size(); i++) {
            TradeGood.validateJsonElement(jsonArrayimports.get(i));
        }
        // ensure the json data is an array
        if (!jsonObj.get("exchange").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `exchange` to be an array in the JSON string but got `%s`",
                jsonObj.get("exchange").toString()));
        }

        JsonArray jsonArrayexchange = jsonObj.getAsJsonArray("exchange");
        // validate the required field `exchange` (array)
        for (int i = 0; i < jsonArrayexchange.size(); i++) {
            TradeGood.validateJsonElement(jsonArrayexchange.get(i));
        }
        if (jsonObj.get("transactions") != null && !jsonObj.get("transactions").isJsonNull()) {
            JsonArray jsonArraytransactions = jsonObj.getAsJsonArray("transactions");
            if (jsonArraytransactions != null) {
                // ensure the json data is an array
                if (!jsonObj.get("transactions").isJsonArray()) {
                    throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                        "Expected the field `transactions` to be an array in the JSON string but got `%s`",
                        jsonObj.get("transactions").toString()));
                }

                // validate the optional field `transactions` (array)
                for (int i = 0; i < jsonArraytransactions.size(); i++) {
                    MarketTransaction.validateJsonElement(jsonArraytransactions.get(i));
                }
            }
        }
        if (jsonObj.get("tradeGoods") != null && !jsonObj.get("tradeGoods").isJsonNull()) {
            JsonArray jsonArraytradeGoods = jsonObj.getAsJsonArray("tradeGoods");
            if (jsonArraytradeGoods != null) {
                // ensure the json data is an array
                if (!jsonObj.get("tradeGoods").isJsonArray()) {
                    throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                        "Expected the field `tradeGoods` to be an array in the JSON string but got `%s`",
                        jsonObj.get("tradeGoods").toString()));
                }

                // validate the optional field `tradeGoods` (array)
                for (int i = 0; i < jsonArraytradeGoods.size(); i++) {
                    MarketTradeGood.validateJsonElement(jsonArraytradeGoods.get(i));
                }
            }
        }
    }

    public void setTransactions(@javax.annotation.Nullable List<MarketTransaction> transactions) {
        this.transactions = transactions;
    }


    public Market tradeGoods(@javax.annotation.Nullable List<MarketTradeGood> tradeGoods) {
        this.tradeGoods = tradeGoods;
        return this;
    }

    public Market addTradeGoodsItem(MarketTradeGood tradeGoodsItem) {
        if (this.tradeGoods == null) {
            this.tradeGoods = new ArrayList<>();
        }
        this.tradeGoods.add(tradeGoodsItem);
        return this;
    }

    /**
     * The symbol of the market. The symbol is the same as the waypoint where the market is
     * located.
     *
     * @return symbol
     */
    @javax.annotation.Nonnull
    public String getSymbol() {
        return symbol;
    }

    public void setTradeGoods(@javax.annotation.Nullable List<MarketTradeGood> tradeGoods) {
        this.tradeGoods = tradeGoods;
    }

    /**
     * The list of recent transactions at this market. Visible only when a ship is present at the
     * market.
     *
     * @return transactions
     */
    @javax.annotation.Nullable
    public List<MarketTransaction> getTransactions() {
        return transactions;
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, exports, imports, exchange, transactions, tradeGoods);
    }

    /**
     * The list of goods that are traded at this market. Visible only when a ship is present at the
     * market.
     *
     * @return tradeGoods
     */
    @javax.annotation.Nullable
    public List<MarketTradeGood> getTradeGoods() {
        return tradeGoods;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Market market = (Market) o;
        return Objects.equals(this.symbol, market.symbol) &&
            Objects.equals(this.exports, market.exports) &&
            Objects.equals(this.imports, market.imports) &&
            Objects.equals(this.exchange, market.exchange) &&
            Objects.equals(this.transactions, market.transactions) &&
            Objects.equals(this.tradeGoods, market.tradeGoods);
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    @Override
    public String toString() {
        String sb = "class Market {\n" +
            "    symbol: " + toIndentedString(symbol) + "\n" +
            "    exports: " + toIndentedString(exports) + "\n" +
            "    imports: " + toIndentedString(imports) + "\n" +
            "    exchange: " + toIndentedString(exchange) + "\n" +
            "    transactions: " + toIndentedString(transactions) + "\n" +
            "    tradeGoods: " + toIndentedString(tradeGoods) + "\n" +
            "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Market.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Market' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Market> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(Market.class));

            return (TypeAdapter<T>) new TypeAdapter<Market>() {
                @Override
                public void write(JsonWriter out, Market value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public Market read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of Market given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of Market
     * @throws IOException if the JSON string is invalid with respect to Market
     */
    public static Market fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, Market.class);
    }

    /**
     * Convert an instance of Market to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

