/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * Meta details for pagination.
 */

public class Meta {

    public static final String SERIALIZED_NAME_TOTAL = "total";
    @SerializedName(SERIALIZED_NAME_TOTAL)
    @javax.annotation.Nonnull
    private Integer total;

    public static final String SERIALIZED_NAME_PAGE = "page";
    @SerializedName(SERIALIZED_NAME_PAGE)
    @javax.annotation.Nonnull
    private Integer page = 1;

    public static final String SERIALIZED_NAME_LIMIT = "limit";
    @SerializedName(SERIALIZED_NAME_LIMIT)
    @javax.annotation.Nonnull
    private Integer limit = 10;

    public Meta() {
    }

    public Meta total(@javax.annotation.Nonnull Integer total) {
        this.total = total;
        return this;
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to Meta
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!Meta.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in Meta is not found in the empty JSON string",
                    Meta.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!Meta.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `Meta` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : Meta.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s", requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public void setTotal(@javax.annotation.Nonnull Integer total) {
        this.total = total;
    }


    public Meta page(@javax.annotation.Nonnull Integer page) {
        this.page = page;
        return this;
    }

    /**
     * Shows the total amount of items of this kind that exist. minimum: 0
     *
     * @return total
     */
    @javax.annotation.Nonnull
    public Integer getTotal() {
        return total;
    }

    public void setPage(@javax.annotation.Nonnull Integer page) {
        this.page = page;
    }


    public Meta limit(@javax.annotation.Nonnull Integer limit) {
        this.limit = limit;
        return this;
    }

    /**
     * A page denotes an amount of items, offset from the first item. Each page holds an amount of
     * items equal to the &#x60;limit&#x60;. minimum: 1
     *
     * @return page
     */
    @javax.annotation.Nonnull
    public Integer getPage() {
        return page;
    }

    public void setLimit(@javax.annotation.Nonnull Integer limit) {
        this.limit = limit;
    }

    /**
     * The amount of items in each page. Limits how many items can be fetched at once. minimum: 1
     * maximum: 20
     *
     * @return limit
     */
    @javax.annotation.Nonnull
    public Integer getLimit() {
        return limit;
    }

    @Override
    public int hashCode() {
        return Objects.hash(total, page, limit);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Meta meta = (Meta) o;
        return Objects.equals(this.total, meta.total) &&
            Objects.equals(this.page, meta.page) &&
            Objects.equals(this.limit, meta.limit);
    }

    @Override
    public String toString() {
        String sb = "class Meta {\n" +
            "    total: " + toIndentedString(total) + "\n" +
            "    page: " + toIndentedString(page) + "\n" +
            "    limit: " + toIndentedString(limit) + "\n" +
            "}";
        return sb;
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("total", "page", "limit"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("total", "page", "limit"));
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Meta.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Meta' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Meta> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(Meta.class));

            return (TypeAdapter<T>) new TypeAdapter<Meta>() {
                @Override
                public void write(JsonWriter out, Meta value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public Meta read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of Meta given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of Meta
     * @throws IOException if the JSON string is invalid with respect to Meta
     */
    public static Meta fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, Meta.class);
    }

    /**
     * Convert an instance of Meta to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

