/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * PurchaseShip201ResponseData
 */

public class PurchaseShip201ResponseData {
    public static final String SERIALIZED_NAME_AGENT = "agent";
    @SerializedName(SERIALIZED_NAME_AGENT)
    @javax.annotation.Nonnull
    private Agent agent;

    public static final String SERIALIZED_NAME_SHIP = "ship";
    @SerializedName(SERIALIZED_NAME_SHIP)
    @javax.annotation.Nonnull
    private Ship ship;

    public static final String SERIALIZED_NAME_TRANSACTION = "transaction";
    @SerializedName(SERIALIZED_NAME_TRANSACTION)
    @javax.annotation.Nonnull
    private ShipyardTransaction transaction;

    public PurchaseShip201ResponseData() {
    }

    public PurchaseShip201ResponseData agent(@javax.annotation.Nonnull Agent agent) {
        this.agent = agent;
        return this;
    }

    /**
     * Get agent
     *
     * @return agent
     */
    @javax.annotation.Nonnull
    public Agent getAgent() {
        return agent;
    }

    public void setAgent(@javax.annotation.Nonnull Agent agent) {
        this.agent = agent;
    }


    public PurchaseShip201ResponseData ship(@javax.annotation.Nonnull Ship ship) {
        this.ship = ship;
        return this;
    }

    /**
     * Get ship
     *
     * @return ship
     */
    @javax.annotation.Nonnull
    public Ship getShip() {
        return ship;
    }

    public void setShip(@javax.annotation.Nonnull Ship ship) {
        this.ship = ship;
    }


    public PurchaseShip201ResponseData transaction(@javax.annotation.Nonnull ShipyardTransaction transaction) {
        this.transaction = transaction;
        return this;
    }

    /**
     * Get transaction
     *
     * @return transaction
     */
    @javax.annotation.Nonnull
    public ShipyardTransaction getTransaction() {
        return transaction;
    }

    public void setTransaction(@javax.annotation.Nonnull ShipyardTransaction transaction) {
        this.transaction = transaction;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PurchaseShip201ResponseData purchaseShip201ResponseData = (PurchaseShip201ResponseData) o;
        return Objects.equals(this.agent, purchaseShip201ResponseData.agent) &&
                Objects.equals(this.ship, purchaseShip201ResponseData.ship) &&
                Objects.equals(this.transaction, purchaseShip201ResponseData.transaction);
    }

    @Override
    public int hashCode() {
        return Objects.hash(agent, ship, transaction);
    }

    @Override
    public String toString() {
        String sb = "class PurchaseShip201ResponseData {\n" +
                "    agent: " + toIndentedString(agent) + "\n" +
                "    ship: " + toIndentedString(ship) + "\n" +
                "    transaction: " + toIndentedString(transaction) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("agent", "ship", "transaction"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("agent", "ship", "transaction"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to PurchaseShip201ResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PurchaseShip201ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PurchaseShip201ResponseData is not found in the empty JSON string", PurchaseShip201ResponseData.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!PurchaseShip201ResponseData.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PurchaseShip201ResponseData` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : PurchaseShip201ResponseData.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `agent`
        Agent.validateJsonElement(jsonObj.get("agent"));
        // validate the required field `ship`
        Ship.validateJsonElement(jsonObj.get("ship"));
        // validate the required field `transaction`
        ShipyardTransaction.validateJsonElement(jsonObj.get("transaction"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PurchaseShip201ResponseData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'PurchaseShip201ResponseData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PurchaseShip201ResponseData> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(PurchaseShip201ResponseData.class));

            return (TypeAdapter<T>) new TypeAdapter<PurchaseShip201ResponseData>() {
                @Override
                public void write(JsonWriter out, PurchaseShip201ResponseData value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public PurchaseShip201ResponseData read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of PurchaseShip201ResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of PurchaseShip201ResponseData
     * @throws IOException if the JSON string is invalid with respect to PurchaseShip201ResponseData
     */
    public static PurchaseShip201ResponseData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PurchaseShip201ResponseData.class);
    }

    /**
     * Convert an instance of PurchaseShip201ResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

