/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * Register201ResponseData
 */

public class Register201ResponseData {

    public static final String SERIALIZED_NAME_AGENT = "agent";
    @SerializedName(SERIALIZED_NAME_AGENT)
    @javax.annotation.Nonnull
    private Agent agent;

    public static final String SERIALIZED_NAME_CONTRACT = "contract";
    @SerializedName(SERIALIZED_NAME_CONTRACT)
    @javax.annotation.Nonnull
    private Contract contract;

    public static final String SERIALIZED_NAME_FACTION = "faction";
    @SerializedName(SERIALIZED_NAME_FACTION)
    @javax.annotation.Nonnull
    private Faction faction;

    public static final String SERIALIZED_NAME_SHIPS = "ships";
    @SerializedName(SERIALIZED_NAME_SHIPS)
    @javax.annotation.Nullable
    private List<Ship> ships = new ArrayList<>();

    public static final String SERIALIZED_NAME_TOKEN = "token";
    @SerializedName(SERIALIZED_NAME_TOKEN)
    @javax.annotation.Nonnull
    private String token;

    public Register201ResponseData() {
    }

    public Register201ResponseData agent(@javax.annotation.Nonnull Agent agent) {
        this.agent = agent;
        return this;
    }

    /**
     * Get agent
     *
     * @return agent
     */
    @javax.annotation.Nonnull
    public Agent getAgent() {
        return agent;
    }

    public void setAgent(@javax.annotation.Nonnull Agent agent) {
        this.agent = agent;
    }


    public Register201ResponseData contract(@javax.annotation.Nonnull Contract contract) {
        this.contract = contract;
        return this;
    }

    /**
     * Get contract
     *
     * @return contract
     */
    @javax.annotation.Nonnull
    public Contract getContract() {
        return contract;
    }

    public void setContract(@javax.annotation.Nonnull Contract contract) {
        this.contract = contract;
    }


    public Register201ResponseData faction(@javax.annotation.Nonnull Faction faction) {
        this.faction = faction;
        return this;
    }

    /**
     * Get faction
     *
     * @return faction
     */
    @javax.annotation.Nonnull
    public Faction getFaction() {
        return faction;
    }

    public void setFaction(@javax.annotation.Nonnull Faction faction) {
        this.faction = faction;
    }


    public Register201ResponseData ships(@javax.annotation.Nullable List<Ship> ships) {
        this.ships = ships;
        return this;
    }

    public Register201ResponseData addShipsItem(Ship shipsItem) {
        if (this.ships == null) {
            this.ships = new ArrayList<>();
        }
        this.ships.add(shipsItem);
        return this;
    }

    /**
     * Get ships
     *
     * @return ships
     */
    @javax.annotation.Nullable
    public List<Ship> getShips() {
        return ships;
    }

    public void setShips(@javax.annotation.Nullable List<Ship> ships) {
        this.ships = ships;
    }


    public Register201ResponseData token(@javax.annotation.Nonnull String token) {
        this.token = token;
        return this;
    }

    /**
     * A Bearer token for accessing secured API endpoints.
     *
     * @return token
     */
    @javax.annotation.Nonnull
    public String getToken() {
        return token;
    }

    public void setToken(@javax.annotation.Nonnull String token) {
        this.token = token;
    }


    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(
            Arrays.asList("agent", "contract", "faction", "ships", "token"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(
            Arrays.asList("agent", "contract", "faction", "token"));
    }

    @Override
    public int hashCode() {
        return Objects.hash(agent, contract, faction, ships, token);
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to Register201ResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!Register201ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in Register201ResponseData is not found in the empty JSON string",
                    Register201ResponseData.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!Register201ResponseData.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `Register201ResponseData` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : Register201ResponseData.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s",
                    requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `agent`
        Agent.validateJsonElement(jsonObj.get("agent"));
        // validate the required field `contract`
        Contract.validateJsonElement(jsonObj.get("contract"));
        // validate the required field `faction`
        Faction.validateJsonElement(jsonObj.get("faction"));
        if (jsonObj.get("ships") != null && !jsonObj.get("ships").isJsonNull()) {
            JsonArray jsonArrayships = jsonObj.getAsJsonArray("ships");
            if (jsonArrayships != null) {
                // ensure the json data is an array
                if (!jsonObj.get("ships").isJsonArray()) {
                    throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                        "Expected the field `ships` to be an array in the JSON string but got `%s`",
                        jsonObj.get("ships").toString()));
                }

                // validate the optional field `ships` (array)
                for (int i = 0; i < jsonArrayships.size(); i++) {
                    Ship.validateJsonElement(jsonArrayships.get(i));
                }
            }
        }
        if (!jsonObj.get("token").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                "Expected the field `token` to be a primitive type in the JSON string but got `%s`",
                jsonObj.get("token").toString()));
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Register201ResponseData register201ResponseData = (Register201ResponseData) o;
        return Objects.equals(this.agent, register201ResponseData.agent) &&
            Objects.equals(this.contract, register201ResponseData.contract) &&
            Objects.equals(this.faction, register201ResponseData.faction) &&
            Objects.equals(this.ships, register201ResponseData.ships) &&
            Objects.equals(this.token, register201ResponseData.token);
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    @Override
    public String toString() {
        String sb = "class Register201ResponseData {\n" +
            "    agent: " + toIndentedString(agent) + "\n" +
            "    contract: " + toIndentedString(contract) + "\n" +
            "    faction: " + toIndentedString(faction) + "\n" +
            "    ships: " + toIndentedString(ships) + "\n" +
            "    token: " + toIndentedString(token) + "\n" +
            "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Register201ResponseData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Register201ResponseData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Register201ResponseData> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(Register201ResponseData.class));

            return (TypeAdapter<T>) new TypeAdapter<Register201ResponseData>() {
                @Override
                public void write(JsonWriter out, Register201ResponseData value)
                    throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public Register201ResponseData read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of Register201ResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of Register201ResponseData
     * @throws IOException if the JSON string is invalid with respect to Register201ResponseData
     */
    public static Register201ResponseData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, Register201ResponseData.class);
    }

    /**
     * Convert an instance of Register201ResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

