/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * Details of a system was that scanned.
 */

public class ScannedSystem {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";
    @SerializedName(SERIALIZED_NAME_SYMBOL)
    @javax.annotation.Nonnull
    private String symbol;

    public static final String SERIALIZED_NAME_SECTOR_SYMBOL = "sectorSymbol";
    @SerializedName(SERIALIZED_NAME_SECTOR_SYMBOL)
    @javax.annotation.Nonnull
    private String sectorSymbol;

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    @javax.annotation.Nonnull
    private SystemType type;

    public static final String SERIALIZED_NAME_X = "x";
    @SerializedName(SERIALIZED_NAME_X)
    @javax.annotation.Nonnull
    private Integer x;

    public static final String SERIALIZED_NAME_Y = "y";
    @SerializedName(SERIALIZED_NAME_Y)
    @javax.annotation.Nonnull
    private Integer y;

    public static final String SERIALIZED_NAME_DISTANCE = "distance";
    @SerializedName(SERIALIZED_NAME_DISTANCE)
    @javax.annotation.Nonnull
    private Integer distance;

    public ScannedSystem() {
    }

    public ScannedSystem symbol(@javax.annotation.Nonnull String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbol of the system.
     *
     * @return symbol
     */
    @javax.annotation.Nonnull
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(@javax.annotation.Nonnull String symbol) {
        this.symbol = symbol;
    }


    public ScannedSystem sectorSymbol(@javax.annotation.Nonnull String sectorSymbol) {
        this.sectorSymbol = sectorSymbol;
        return this;
    }

    /**
     * Symbol of the system&#39;s sector.
     *
     * @return sectorSymbol
     */
    @javax.annotation.Nonnull
    public String getSectorSymbol() {
        return sectorSymbol;
    }

    public void setSectorSymbol(@javax.annotation.Nonnull String sectorSymbol) {
        this.sectorSymbol = sectorSymbol;
    }


    public ScannedSystem type(@javax.annotation.Nonnull SystemType type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @javax.annotation.Nonnull
    public SystemType getType() {
        return type;
    }

    public void setType(@javax.annotation.Nonnull SystemType type) {
        this.type = type;
    }


    public ScannedSystem x(@javax.annotation.Nonnull Integer x) {
        this.x = x;
        return this;
    }

    /**
     * Position in the universe in the x axis.
     *
     * @return x
     */
    @javax.annotation.Nonnull
    public Integer getX() {
        return x;
    }

    public void setX(@javax.annotation.Nonnull Integer x) {
        this.x = x;
    }


    public ScannedSystem y(@javax.annotation.Nonnull Integer y) {
        this.y = y;
        return this;
    }

    /**
     * Position in the universe in the y axis.
     *
     * @return y
     */
    @javax.annotation.Nonnull
    public Integer getY() {
        return y;
    }

    public void setY(@javax.annotation.Nonnull Integer y) {
        this.y = y;
    }


    public ScannedSystem distance(@javax.annotation.Nonnull Integer distance) {
        this.distance = distance;
        return this;
    }

    /**
     * The system&#39;s distance from the scanning ship.
     *
     * @return distance
     */
    @javax.annotation.Nonnull
    public Integer getDistance() {
        return distance;
    }

    public void setDistance(@javax.annotation.Nonnull Integer distance) {
        this.distance = distance;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ScannedSystem scannedSystem = (ScannedSystem) o;
        return Objects.equals(this.symbol, scannedSystem.symbol) &&
                Objects.equals(this.sectorSymbol, scannedSystem.sectorSymbol) &&
                Objects.equals(this.type, scannedSystem.type) &&
                Objects.equals(this.x, scannedSystem.x) &&
                Objects.equals(this.y, scannedSystem.y) &&
                Objects.equals(this.distance, scannedSystem.distance);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, sectorSymbol, type, x, y, distance);
    }

    @Override
    public String toString() {
        String sb = "class ScannedSystem {\n" +
                "    symbol: " + toIndentedString(symbol) + "\n" +
                "    sectorSymbol: " + toIndentedString(sectorSymbol) + "\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    x: " + toIndentedString(x) + "\n" +
                "    y: " + toIndentedString(y) + "\n" +
                "    distance: " + toIndentedString(distance) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("symbol", "sectorSymbol", "type", "x", "y", "distance"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("symbol", "sectorSymbol", "type", "x", "y", "distance"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ScannedSystem
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ScannedSystem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ScannedSystem is not found in the empty JSON string", ScannedSystem.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ScannedSystem.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ScannedSystem` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ScannedSystem.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("symbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
        }
        if (!jsonObj.get("sectorSymbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sectorSymbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sectorSymbol").toString()));
        }
        // validate the required field `type`
        SystemType.validateJsonElement(jsonObj.get("type"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ScannedSystem.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ScannedSystem' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ScannedSystem> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(ScannedSystem.class));

            return (TypeAdapter<T>) new TypeAdapter<ScannedSystem>() {
                @Override
                public void write(JsonWriter out, ScannedSystem value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ScannedSystem read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ScannedSystem given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ScannedSystem
     * @throws IOException if the JSON string is invalid with respect to ScannedSystem
     */
    public static ScannedSystem fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ScannedSystem.class);
    }

    /**
     * Convert an instance of ScannedSystem to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

