/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * The ship&#39;s crew service and maintain the ship&#39;s systems and equipment.
 */
public class ShipCrew {
    public static final String SERIALIZED_NAME_CURRENT = "current";
    @SerializedName(SERIALIZED_NAME_CURRENT)
    @javax.annotation.Nonnull
    private Integer current;

    public static final String SERIALIZED_NAME_REQUIRED = "required";
    @SerializedName(SERIALIZED_NAME_REQUIRED)
    @javax.annotation.Nonnull
    private Integer required;

    public static final String SERIALIZED_NAME_CAPACITY = "capacity";
    @SerializedName(SERIALIZED_NAME_CAPACITY)
    @javax.annotation.Nonnull
    private Integer capacity;

    /**
     * The rotation of crew shifts. A stricter shift improves the ship&#39;s performance. A more relaxed shift improves the crew&#39;s morale.
     */
    @JsonAdapter(RotationEnum.Adapter.class)
    public enum RotationEnum {
        STRICT("STRICT"),

        RELAXED("RELAXED");

        private final String value;

        RotationEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static RotationEnum fromValue(String value) {
            for (RotationEnum b : RotationEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<RotationEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final RotationEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public RotationEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return RotationEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            RotationEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_ROTATION = "rotation";
    @SerializedName(SERIALIZED_NAME_ROTATION)
    @javax.annotation.Nonnull
    private RotationEnum rotation = RotationEnum.STRICT;

    public static final String SERIALIZED_NAME_MORALE = "morale";
    @SerializedName(SERIALIZED_NAME_MORALE)
    @javax.annotation.Nonnull
    private Integer morale;

    public static final String SERIALIZED_NAME_WAGES = "wages";
    @SerializedName(SERIALIZED_NAME_WAGES)
    @javax.annotation.Nonnull
    private Integer wages;

    public ShipCrew() {
    }

    public ShipCrew current(@javax.annotation.Nonnull Integer current) {
        this.current = current;
        return this;
    }

    /**
     * The current number of crew members on the ship.
     *
     * @return current
     */
    @javax.annotation.Nonnull
    public Integer getCurrent() {
        return current;
    }

    public void setCurrent(@javax.annotation.Nonnull Integer current) {
        this.current = current;
    }


    public ShipCrew required(@javax.annotation.Nonnull Integer required) {
        this.required = required;
        return this;
    }

    /**
     * The minimum number of crew members required to maintain the ship.
     *
     * @return required
     */
    @javax.annotation.Nonnull
    public Integer getRequired() {
        return required;
    }

    public void setRequired(@javax.annotation.Nonnull Integer required) {
        this.required = required;
    }


    public ShipCrew capacity(@javax.annotation.Nonnull Integer capacity) {
        this.capacity = capacity;
        return this;
    }

    /**
     * The maximum number of crew members the ship can support.
     *
     * @return capacity
     */
    @javax.annotation.Nonnull
    public Integer getCapacity() {
        return capacity;
    }

    public void setCapacity(@javax.annotation.Nonnull Integer capacity) {
        this.capacity = capacity;
    }


    public ShipCrew rotation(@javax.annotation.Nonnull RotationEnum rotation) {
        this.rotation = rotation;
        return this;
    }

    /**
     * The rotation of crew shifts. A stricter shift improves the ship&#39;s performance. A more relaxed shift improves the crew&#39;s morale.
     *
     * @return rotation
     */
    @javax.annotation.Nonnull
    public RotationEnum getRotation() {
        return rotation;
    }

    public void setRotation(@javax.annotation.Nonnull RotationEnum rotation) {
        this.rotation = rotation;
    }


    public ShipCrew morale(@javax.annotation.Nonnull Integer morale) {
        this.morale = morale;
        return this;
    }

    /**
     * A rough measure of the crew&#39;s morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.
     * minimum: 0
     * maximum: 100
     *
     * @return morale
     */
    @javax.annotation.Nonnull
    public Integer getMorale() {
        return morale;
    }

    public void setMorale(@javax.annotation.Nonnull Integer morale) {
        this.morale = morale;
    }


    public ShipCrew wages(@javax.annotation.Nonnull Integer wages) {
        this.wages = wages;
        return this;
    }

    /**
     * The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.
     * minimum: 0
     *
     * @return wages
     */
    @javax.annotation.Nonnull
    public Integer getWages() {
        return wages;
    }

    public void setWages(@javax.annotation.Nonnull Integer wages) {
        this.wages = wages;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipCrew shipCrew = (ShipCrew) o;
        return Objects.equals(this.current, shipCrew.current) &&
                Objects.equals(this.required, shipCrew.required) &&
                Objects.equals(this.capacity, shipCrew.capacity) &&
                Objects.equals(this.rotation, shipCrew.rotation) &&
                Objects.equals(this.morale, shipCrew.morale) &&
                Objects.equals(this.wages, shipCrew.wages);
    }

    @Override
    public int hashCode() {
        return Objects.hash(current, required, capacity, rotation, morale, wages);
    }

    @Override
    public String toString() {
        String sb = "class ShipCrew {\n" +
                "    current: " + toIndentedString(current) + "\n" +
                "    required: " + toIndentedString(required) + "\n" +
                "    capacity: " + toIndentedString(capacity) + "\n" +
                "    rotation: " + toIndentedString(rotation) + "\n" +
                "    morale: " + toIndentedString(morale) + "\n" +
                "    wages: " + toIndentedString(wages) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("current", "required", "capacity", "rotation", "morale", "wages"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("current", "required", "capacity", "rotation", "morale", "wages"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ShipCrew
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ShipCrew.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ShipCrew is not found in the empty JSON string", ShipCrew.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ShipCrew.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ShipCrew` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ShipCrew.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("rotation").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rotation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rotation").toString()));
        }
        // validate the required field `rotation`
        RotationEnum.validateJsonElement(jsonObj.get("rotation"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ShipCrew.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ShipCrew' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ShipCrew> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(ShipCrew.class));

            return (TypeAdapter<T>) new TypeAdapter<ShipCrew>() {
                @Override
                public void write(JsonWriter out, ShipCrew value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ShipCrew read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ShipCrew given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ShipCrew
     * @throws IOException if the JSON string is invalid with respect to ShipCrew
     */
    public static ShipCrew fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ShipCrew.class);
    }

    /**
     * Convert an instance of ShipCrew to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

