/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.*;

/**
 * The engine determines how quickly a ship travels between waypoints.
 */

public class ShipEngine {
    /**
     * The symbol of the engine.
     */
    @JsonAdapter(SymbolEnum.Adapter.class)
    public enum SymbolEnum {
        ENGINE_IMPULSE_DRIVE_I("ENGINE_IMPULSE_DRIVE_I"),

        ENGINE_ION_DRIVE_I("ENGINE_ION_DRIVE_I"),

        ENGINE_ION_DRIVE_II("ENGINE_ION_DRIVE_II"),

        ENGINE_HYPER_DRIVE_I("ENGINE_HYPER_DRIVE_I");

        private final String value;

        SymbolEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static SymbolEnum fromValue(String value) {
            for (SymbolEnum b : SymbolEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<SymbolEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final SymbolEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public SymbolEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return SymbolEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            SymbolEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";
    @SerializedName(SERIALIZED_NAME_SYMBOL)
    @javax.annotation.Nonnull
    private SymbolEnum symbol;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    @javax.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";
    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @javax.annotation.Nonnull
    private String description;

    public static final String SERIALIZED_NAME_CONDITION = "condition";
    @SerializedName(SERIALIZED_NAME_CONDITION)
    @javax.annotation.Nonnull
    private Double condition;

    public static final String SERIALIZED_NAME_INTEGRITY = "integrity";
    @SerializedName(SERIALIZED_NAME_INTEGRITY)
    @javax.annotation.Nonnull
    private Double integrity;

    public static final String SERIALIZED_NAME_SPEED = "speed";
    @SerializedName(SERIALIZED_NAME_SPEED)
    @javax.annotation.Nonnull
    private Integer speed;

    public static final String SERIALIZED_NAME_REQUIREMENTS = "requirements";
    @SerializedName(SERIALIZED_NAME_REQUIREMENTS)
    @javax.annotation.Nonnull
    private ShipRequirements requirements;

    public static final String SERIALIZED_NAME_QUALITY = "quality";
    @SerializedName(SERIALIZED_NAME_QUALITY)
    @javax.annotation.Nonnull
    private BigDecimal quality;

    public ShipEngine() {
    }

    public ShipEngine symbol(@javax.annotation.Nonnull SymbolEnum symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * The symbol of the engine.
     *
     * @return symbol
     */
    @javax.annotation.Nonnull
    public SymbolEnum getSymbol() {
        return symbol;
    }

    public void setSymbol(@javax.annotation.Nonnull SymbolEnum symbol) {
        this.symbol = symbol;
    }


    public ShipEngine name(@javax.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * The name of the engine.
     *
     * @return name
     */
    @javax.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@javax.annotation.Nonnull String name) {
        this.name = name;
    }


    public ShipEngine description(@javax.annotation.Nonnull String description) {
        this.description = description;
        return this;
    }

    /**
     * The description of the engine.
     *
     * @return description
     */
    @javax.annotation.Nonnull
    public String getDescription() {
        return description;
    }

    public void setDescription(@javax.annotation.Nonnull String description) {
        this.description = description;
    }


    public ShipEngine condition(@javax.annotation.Nonnull Double condition) {
        this.condition = condition;
        return this;
    }

    /**
     * The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
     * minimum: 0
     * maximum: 1
     *
     * @return condition
     */
    @javax.annotation.Nonnull
    public Double getCondition() {
        return condition;
    }

    public void setCondition(@javax.annotation.Nonnull Double condition) {
        this.condition = condition;
    }


    public ShipEngine integrity(@javax.annotation.Nonnull Double integrity) {
        this.integrity = integrity;
        return this;
    }

    /**
     * The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
     * minimum: 0
     * maximum: 1
     *
     * @return integrity
     */
    @javax.annotation.Nonnull
    public Double getIntegrity() {
        return integrity;
    }

    public void setIntegrity(@javax.annotation.Nonnull Double integrity) {
        this.integrity = integrity;
    }


    public ShipEngine speed(@javax.annotation.Nonnull Integer speed) {
        this.speed = speed;
        return this;
    }

    /**
     * The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.
     * minimum: 1
     *
     * @return speed
     */
    @javax.annotation.Nonnull
    public Integer getSpeed() {
        return speed;
    }

    public void setSpeed(@javax.annotation.Nonnull Integer speed) {
        this.speed = speed;
    }


    public ShipEngine requirements(@javax.annotation.Nonnull ShipRequirements requirements) {
        this.requirements = requirements;
        return this;
    }

    /**
     * Get requirements
     *
     * @return requirements
     */
    @javax.annotation.Nonnull
    public ShipRequirements getRequirements() {
        return requirements;
    }

    public void setRequirements(@javax.annotation.Nonnull ShipRequirements requirements) {
        this.requirements = requirements;
    }


    public ShipEngine quality(@javax.annotation.Nonnull BigDecimal quality) {
        this.quality = quality;
        return this;
    }

    /**
     * The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.
     *
     * @return quality
     */
    @javax.annotation.Nonnull
    public BigDecimal getQuality() {
        return quality;
    }

    public void setQuality(@javax.annotation.Nonnull BigDecimal quality) {
        this.quality = quality;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipEngine shipEngine = (ShipEngine) o;
        return Objects.equals(this.symbol, shipEngine.symbol) &&
                Objects.equals(this.name, shipEngine.name) &&
                Objects.equals(this.description, shipEngine.description) &&
                Objects.equals(this.condition, shipEngine.condition) &&
                Objects.equals(this.integrity, shipEngine.integrity) &&
                Objects.equals(this.speed, shipEngine.speed) &&
                Objects.equals(this.requirements, shipEngine.requirements) &&
                Objects.equals(this.quality, shipEngine.quality);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, name, description, condition, integrity, speed, requirements, quality);
    }

    @Override
    public String toString() {
        String sb = "class ShipEngine {\n" +
                "    symbol: " + toIndentedString(symbol) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    condition: " + toIndentedString(condition) + "\n" +
                "    integrity: " + toIndentedString(integrity) + "\n" +
                "    speed: " + toIndentedString(speed) + "\n" +
                "    requirements: " + toIndentedString(requirements) + "\n" +
                "    quality: " + toIndentedString(quality) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("symbol", "name", "description", "condition", "integrity", "speed", "requirements", "quality"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("symbol", "name", "description", "condition", "integrity", "speed", "requirements", "quality"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ShipEngine
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ShipEngine.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ShipEngine is not found in the empty JSON string", ShipEngine.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ShipEngine.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ShipEngine` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ShipEngine.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("symbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
        }
        // validate the required field `symbol`
        SymbolEnum.validateJsonElement(jsonObj.get("symbol"));
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
        }
        if (!jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
        }
        // validate the required field `requirements`
        ShipRequirements.validateJsonElement(jsonObj.get("requirements"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ShipEngine.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ShipEngine' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ShipEngine> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(ShipEngine.class));

            return (TypeAdapter<T>) new TypeAdapter<ShipEngine>() {
                @Override
                public void write(JsonWriter out, ShipEngine value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ShipEngine read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ShipEngine given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ShipEngine
     * @throws IOException if the JSON string is invalid with respect to ShipEngine
     */
    public static ShipEngine fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ShipEngine.class);
    }

    /**
     * Convert an instance of ShipEngine to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

