/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * Ship cargo details.
 */

public class ShipCargo {
    public static final String SERIALIZED_NAME_CAPACITY = "capacity";
    @SerializedName(SERIALIZED_NAME_CAPACITY)
    @javax.annotation.Nonnull
    private Integer capacity;

    public static final String SERIALIZED_NAME_UNITS = "units";
    @SerializedName(SERIALIZED_NAME_UNITS)
    @javax.annotation.Nonnull
    private Integer units;

    public static final String SERIALIZED_NAME_INVENTORY = "inventory";
    @SerializedName(SERIALIZED_NAME_INVENTORY)
    @javax.annotation.Nonnull
    private List<ShipCargoItem> inventory = new ArrayList<>();

    public ShipCargo() {
    }

    public ShipCargo capacity(@javax.annotation.Nonnull Integer capacity) {
        this.capacity = capacity;
        return this;
    }

    /**
     * The max number of items that can be stored in the cargo hold.
     * minimum: 0
     *
     * @return capacity
     */
    @javax.annotation.Nonnull
    public Integer getCapacity() {
        return capacity;
    }

    public void setCapacity(@javax.annotation.Nonnull Integer capacity) {
        this.capacity = capacity;
    }


    public ShipCargo units(@javax.annotation.Nonnull Integer units) {
        this.units = units;
        return this;
    }

    /**
     * The number of items currently stored in the cargo hold.
     * minimum: 0
     *
     * @return units
     */
    @javax.annotation.Nonnull
    public Integer getUnits() {
        return units;
    }

    public void setUnits(@javax.annotation.Nonnull Integer units) {
        this.units = units;
    }


    public ShipCargo inventory(@javax.annotation.Nonnull List<ShipCargoItem> inventory) {
        this.inventory = inventory;
        return this;
    }

    public ShipCargo addInventoryItem(ShipCargoItem inventoryItem) {
        if (this.inventory == null) {
            this.inventory = new ArrayList<>();
        }
        this.inventory.add(inventoryItem);
        return this;
    }

    /**
     * The items currently in the cargo hold.
     *
     * @return inventory
     */
    @javax.annotation.Nonnull
    public List<ShipCargoItem> getInventory() {
        return inventory;
    }

    public void setInventory(@javax.annotation.Nonnull List<ShipCargoItem> inventory) {
        this.inventory = inventory;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipCargo shipCargo = (ShipCargo) o;
        return Objects.equals(this.capacity, shipCargo.capacity) &&
                Objects.equals(this.units, shipCargo.units) &&
                Objects.equals(this.inventory, shipCargo.inventory);
    }

    @Override
    public int hashCode() {
        return Objects.hash(capacity, units, inventory);
    }

    @Override
    public String toString() {
        String sb = "class ShipCargo {\n" +
                "    capacity: " + toIndentedString(capacity) + "\n" +
                "    units: " + toIndentedString(units) + "\n" +
                "    inventory: " + toIndentedString(inventory) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("capacity", "units", "inventory"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("capacity", "units", "inventory"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ShipCargo
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ShipCargo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ShipCargo is not found in the empty JSON string", ShipCargo.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ShipCargo.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ShipCargo` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ShipCargo.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // ensure the json data is an array
        if (!jsonObj.get("inventory").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inventory` to be an array in the JSON string but got `%s`", jsonObj.get("inventory").toString()));
        }

        JsonArray jsonArrayinventory = jsonObj.getAsJsonArray("inventory");
        // validate the required field `inventory` (array)
        for (int i = 0; i < jsonArrayinventory.size(); i++) {
            ShipCargoItem.validateJsonElement(jsonArrayinventory.get(i));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ShipCargo.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ShipCargo' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ShipCargo> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(ShipCargo.class));

            return (TypeAdapter<T>) new TypeAdapter<ShipCargo>() {
                @Override
                public void write(JsonWriter out, ShipCargo value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ShipCargo read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ShipCargo given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ShipCargo
     * @throws IOException if the JSON string is invalid with respect to ShipCargo
     */
    public static ShipCargo fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ShipCargo.class);
    }

    /**
     * Convert an instance of ShipCargo to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

