/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.persistence.Embeddable;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import xyz.faria.space.spaceapi.client.JSON;

/**
 * An object that only shows up when an action has consumed fuel in the process. Shows the fuel
 * consumption data.
 */
@Embeddable
public class ShipFuelConsumed {

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    @javax.annotation.Nonnull
    private Integer amount;

    public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
    @SerializedName(SERIALIZED_NAME_TIMESTAMP)
    @javax.annotation.Nonnull
    private OffsetDateTime timestamp;

    public ShipFuelConsumed() {
    }

    public ShipFuelConsumed amount(@javax.annotation.Nonnull Integer amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ShipFuelConsumed
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ShipFuelConsumed.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field(s) %s in ShipFuelConsumed is not found in the empty JSON string",
                    ShipFuelConsumed.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ShipFuelConsumed.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The field `%s` in the JSON string is not defined in the `ShipFuelConsumed` properties. JSON: %s",
                    entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ShipFuelConsumed.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "The required field `%s` is not found in the JSON string: %s",
                    requiredField,
                    jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public void setAmount(@javax.annotation.Nonnull Integer amount) {
        this.amount = amount;
    }


    public ShipFuelConsumed timestamp(@javax.annotation.Nonnull OffsetDateTime timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * The time at which the fuel was consumed.
     *
     * @return timestamp
     */
    @javax.annotation.Nonnull
    public OffsetDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(@javax.annotation.Nonnull OffsetDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * The amount of fuel consumed by the most recent transit or action. minimum: 0
     *
     * @return amount
     */
    @javax.annotation.Nonnull
    public Integer getAmount() {
        return amount;
    }

    @Override
    public int hashCode() {
        return Objects.hash(amount, timestamp);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipFuelConsumed shipFuelConsumed = (ShipFuelConsumed) o;
        return Objects.equals(this.amount, shipFuelConsumed.amount) &&
            Objects.equals(this.timestamp, shipFuelConsumed.timestamp);
    }

    @Override
    public String toString() {
        String sb = "class ShipFuelConsumed {\n" +
            "    amount: " + toIndentedString(amount) + "\n" +
            "    timestamp: " + toIndentedString(timestamp) + "\n" +
            "}";
        return sb;
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("amount", "timestamp"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("amount", "timestamp"));
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ShipFuelConsumed.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ShipFuelConsumed' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ShipFuelConsumed> thisAdapter
                = gson.getDelegateAdapter(this, TypeToken.get(ShipFuelConsumed.class));

            return (TypeAdapter<T>) new TypeAdapter<ShipFuelConsumed>() {
                @Override
                public void write(JsonWriter out, ShipFuelConsumed value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ShipFuelConsumed read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ShipFuelConsumed given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ShipFuelConsumed
     * @throws IOException if the JSON string is invalid with respect to ShipFuelConsumed
     */
    public static ShipFuelConsumed fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ShipFuelConsumed.class);
    }

    /**
     * Convert an instance of ShipFuelConsumed to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

