/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * A mount is installed on the exterier of a ship.
 */
public class ShipMount {
    /**
     * Symbo of this mount.
     */
    @JsonAdapter(SymbolEnum.Adapter.class)
    public enum SymbolEnum {
        MOUNT_GAS_SIPHON_I("MOUNT_GAS_SIPHON_I"),

        MOUNT_GAS_SIPHON_II("MOUNT_GAS_SIPHON_II"),

        MOUNT_GAS_SIPHON_III("MOUNT_GAS_SIPHON_III"),

        MOUNT_SURVEYOR_I("MOUNT_SURVEYOR_I"),

        MOUNT_SURVEYOR_II("MOUNT_SURVEYOR_II"),

        MOUNT_SURVEYOR_III("MOUNT_SURVEYOR_III"),

        MOUNT_SENSOR_ARRAY_I("MOUNT_SENSOR_ARRAY_I"),

        MOUNT_SENSOR_ARRAY_II("MOUNT_SENSOR_ARRAY_II"),

        MOUNT_SENSOR_ARRAY_III("MOUNT_SENSOR_ARRAY_III"),

        MOUNT_MINING_LASER_I("MOUNT_MINING_LASER_I"),

        MOUNT_MINING_LASER_II("MOUNT_MINING_LASER_II"),

        MOUNT_MINING_LASER_III("MOUNT_MINING_LASER_III"),

        MOUNT_LASER_CANNON_I("MOUNT_LASER_CANNON_I"),

        MOUNT_MISSILE_LAUNCHER_I("MOUNT_MISSILE_LAUNCHER_I"),

        MOUNT_TURRET_I("MOUNT_TURRET_I");

        private final String value;

        SymbolEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static SymbolEnum fromValue(String value) {
            for (SymbolEnum b : SymbolEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<SymbolEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final SymbolEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public SymbolEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return SymbolEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            SymbolEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";
    @SerializedName(SERIALIZED_NAME_SYMBOL)
    @javax.annotation.Nonnull
    private SymbolEnum symbol;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    @javax.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";
    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @javax.annotation.Nullable
    private String description;

    public static final String SERIALIZED_NAME_STRENGTH = "strength";
    @SerializedName(SERIALIZED_NAME_STRENGTH)
    @javax.annotation.Nullable
    private Integer strength;

    /**
     * Gets or Sets deposits
     */
    @JsonAdapter(DepositsEnum.Adapter.class)
    public enum DepositsEnum {
        QUARTZ_SAND("QUARTZ_SAND"),

        SILICON_CRYSTALS("SILICON_CRYSTALS"),

        PRECIOUS_STONES("PRECIOUS_STONES"),

        ICE_WATER("ICE_WATER"),

        AMMONIA_ICE("AMMONIA_ICE"),

        IRON_ORE("IRON_ORE"),

        COPPER_ORE("COPPER_ORE"),

        SILVER_ORE("SILVER_ORE"),

        ALUMINUM_ORE("ALUMINUM_ORE"),

        GOLD_ORE("GOLD_ORE"),

        PLATINUM_ORE("PLATINUM_ORE"),

        DIAMONDS("DIAMONDS"),

        URANITE_ORE("URANITE_ORE"),

        MERITIUM_ORE("MERITIUM_ORE");

        private final String value;

        DepositsEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static DepositsEnum fromValue(String value) {
            for (DepositsEnum b : DepositsEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<DepositsEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final DepositsEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public DepositsEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return DepositsEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            DepositsEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_DEPOSITS = "deposits";
    @SerializedName(SERIALIZED_NAME_DEPOSITS)
    @javax.annotation.Nullable
    private List<DepositsEnum> deposits = new ArrayList<>();

    public static final String SERIALIZED_NAME_REQUIREMENTS = "requirements";
    @SerializedName(SERIALIZED_NAME_REQUIREMENTS)
    @javax.annotation.Nonnull
    private ShipRequirements requirements;

    public ShipMount() {
    }

    public ShipMount symbol(@javax.annotation.Nonnull SymbolEnum symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Symbo of this mount.
     *
     * @return symbol
     */
    @javax.annotation.Nonnull
    public SymbolEnum getSymbol() {
        return symbol;
    }

    public void setSymbol(@javax.annotation.Nonnull SymbolEnum symbol) {
        this.symbol = symbol;
    }


    public ShipMount name(@javax.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Name of this mount.
     *
     * @return name
     */
    @javax.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@javax.annotation.Nonnull String name) {
        this.name = name;
    }


    public ShipMount description(@javax.annotation.Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Description of this mount.
     *
     * @return description
     */
    @javax.annotation.Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@javax.annotation.Nullable String description) {
        this.description = description;
    }


    public ShipMount strength(@javax.annotation.Nullable Integer strength) {
        this.strength = strength;
        return this;
    }

    /**
     * Mounts that have this value, such as mining lasers, denote how powerful this mount&#39;s capabilities are.
     * minimum: 0
     *
     * @return strength
     */
    @javax.annotation.Nullable
    public Integer getStrength() {
        return strength;
    }

    public void setStrength(@javax.annotation.Nullable Integer strength) {
        this.strength = strength;
    }


    public ShipMount deposits(@javax.annotation.Nullable List<DepositsEnum> deposits) {
        this.deposits = deposits;
        return this;
    }

    public ShipMount addDepositsItem(DepositsEnum depositsItem) {
        if (this.deposits == null) {
            this.deposits = new ArrayList<>();
        }
        this.deposits.add(depositsItem);
        return this;
    }

    /**
     * Mounts that have this value denote what goods can be produced from using the mount.
     *
     * @return deposits
     */
    @javax.annotation.Nullable
    public List<DepositsEnum> getDeposits() {
        return deposits;
    }

    public void setDeposits(@javax.annotation.Nullable List<DepositsEnum> deposits) {
        this.deposits = deposits;
    }


    public ShipMount requirements(@javax.annotation.Nonnull ShipRequirements requirements) {
        this.requirements = requirements;
        return this;
    }

    /**
     * Get requirements
     *
     * @return requirements
     */
    @javax.annotation.Nonnull
    public ShipRequirements getRequirements() {
        return requirements;
    }

    public void setRequirements(@javax.annotation.Nonnull ShipRequirements requirements) {
        this.requirements = requirements;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipMount shipMount = (ShipMount) o;
        return Objects.equals(this.symbol, shipMount.symbol) &&
                Objects.equals(this.name, shipMount.name) &&
                Objects.equals(this.description, shipMount.description) &&
                Objects.equals(this.strength, shipMount.strength) &&
                Objects.equals(this.deposits, shipMount.deposits) &&
                Objects.equals(this.requirements, shipMount.requirements);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, name, description, strength, deposits, requirements);
    }

    @Override
    public String toString() {
        String sb = "class ShipMount {\n" +
                "    symbol: " + toIndentedString(symbol) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    strength: " + toIndentedString(strength) + "\n" +
                "    deposits: " + toIndentedString(deposits) + "\n" +
                "    requirements: " + toIndentedString(requirements) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("symbol", "name", "description", "strength", "deposits", "requirements"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("symbol", "name", "requirements"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ShipMount
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ShipMount.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ShipMount is not found in the empty JSON string", ShipMount.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ShipMount.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ShipMount` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ShipMount.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("symbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
        }
        // validate the required field `symbol`
        SymbolEnum.validateJsonElement(jsonObj.get("symbol"));
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
        }
        if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("deposits") != null && !jsonObj.get("deposits").isJsonNull() && !jsonObj.get("deposits").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `deposits` to be an array in the JSON string but got `%s`", jsonObj.get("deposits").toString()));
        }
        // validate the required field `requirements`
        ShipRequirements.validateJsonElement(jsonObj.get("requirements"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ShipMount.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ShipMount' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ShipMount> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(ShipMount.class));

            return (TypeAdapter<T>) new TypeAdapter<ShipMount>() {
                @Override
                public void write(JsonWriter out, ShipMount value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ShipMount read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ShipMount given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ShipMount
     * @throws IOException if the JSON string is invalid with respect to ShipMount
     */
    public static ShipMount fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ShipMount.class);
    }

    /**
     * Convert an instance of ShipMount to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

