/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * The requirements for installation on a ship
 */
public class ShipRequirements {
    public static final String SERIALIZED_NAME_POWER = "power";
    @SerializedName(SERIALIZED_NAME_POWER)
    @javax.annotation.Nullable
    private Integer power;

    public static final String SERIALIZED_NAME_CREW = "crew";
    @SerializedName(SERIALIZED_NAME_CREW)
    @javax.annotation.Nullable
    private Integer crew;

    public static final String SERIALIZED_NAME_SLOTS = "slots";
    @SerializedName(SERIALIZED_NAME_SLOTS)
    @javax.annotation.Nullable
    private Integer slots;

    public ShipRequirements() {
    }

    public ShipRequirements power(@javax.annotation.Nullable Integer power) {
        this.power = power;
        return this;
    }

    /**
     * The amount of power required from the reactor.
     *
     * @return power
     */
    @javax.annotation.Nullable
    public Integer getPower() {
        return power;
    }

    public void setPower(@javax.annotation.Nullable Integer power) {
        this.power = power;
    }


    public ShipRequirements crew(@javax.annotation.Nullable Integer crew) {
        this.crew = crew;
        return this;
    }

    /**
     * The number of crew required for operation.
     *
     * @return crew
     */
    @javax.annotation.Nullable
    public Integer getCrew() {
        return crew;
    }

    public void setCrew(@javax.annotation.Nullable Integer crew) {
        this.crew = crew;
    }


    public ShipRequirements slots(@javax.annotation.Nullable Integer slots) {
        this.slots = slots;
        return this;
    }

    /**
     * The number of module slots required for installation.
     *
     * @return slots
     */
    @javax.annotation.Nullable
    public Integer getSlots() {
        return slots;
    }

    public void setSlots(@javax.annotation.Nullable Integer slots) {
        this.slots = slots;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipRequirements shipRequirements = (ShipRequirements) o;
        return Objects.equals(this.power, shipRequirements.power) &&
                Objects.equals(this.crew, shipRequirements.crew) &&
                Objects.equals(this.slots, shipRequirements.slots);
    }

    @Override
    public int hashCode() {
        return Objects.hash(power, crew, slots);
    }

    @Override
    public String toString() {
        String sb = "class ShipRequirements {\n" +
                "    power: " + toIndentedString(power) + "\n" +
                "    crew: " + toIndentedString(crew) + "\n" +
                "    slots: " + toIndentedString(slots) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("power", "crew", "slots"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(0);
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ShipRequirements
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ShipRequirements.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ShipRequirements is not found in the empty JSON string", ShipRequirements.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ShipRequirements.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ShipRequirements` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ShipRequirements.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ShipRequirements' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ShipRequirements> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(ShipRequirements.class));

            return (TypeAdapter<T>) new TypeAdapter<ShipRequirements>() {
                @Override
                public void write(JsonWriter out, ShipRequirements value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public ShipRequirements read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of ShipRequirements given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ShipRequirements
     * @throws IOException if the JSON string is invalid with respect to ShipRequirements
     */
    public static ShipRequirements fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ShipRequirements.class);
    }

    /**
     * Convert an instance of ShipRequirements to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

