/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * SiphonResources201ResponseData
 */
public class SiphonResources201ResponseData {
    public static final String SERIALIZED_NAME_COOLDOWN = "cooldown";
    @SerializedName(SERIALIZED_NAME_COOLDOWN)
    @javax.annotation.Nonnull
    private Cooldown cooldown;

    public static final String SERIALIZED_NAME_SIPHON = "siphon";
    @SerializedName(SERIALIZED_NAME_SIPHON)
    @javax.annotation.Nonnull
    private Siphon siphon;

    public static final String SERIALIZED_NAME_CARGO = "cargo";
    @SerializedName(SERIALIZED_NAME_CARGO)
    @javax.annotation.Nonnull
    private ShipCargo cargo;

    public static final String SERIALIZED_NAME_EVENTS = "events";
    @SerializedName(SERIALIZED_NAME_EVENTS)
    @javax.annotation.Nonnull
    private List<ShipConditionEvent> events = new ArrayList<>();

    public SiphonResources201ResponseData() {
    }

    public SiphonResources201ResponseData cooldown(@javax.annotation.Nonnull Cooldown cooldown) {
        this.cooldown = cooldown;
        return this;
    }

    /**
     * Get cooldown
     *
     * @return cooldown
     */
    @javax.annotation.Nonnull
    public Cooldown getCooldown() {
        return cooldown;
    }

    public void setCooldown(@javax.annotation.Nonnull Cooldown cooldown) {
        this.cooldown = cooldown;
    }


    public SiphonResources201ResponseData siphon(@javax.annotation.Nonnull Siphon siphon) {
        this.siphon = siphon;
        return this;
    }

    /**
     * Get siphon
     *
     * @return siphon
     */
    @javax.annotation.Nonnull
    public Siphon getSiphon() {
        return siphon;
    }

    public void setSiphon(@javax.annotation.Nonnull Siphon siphon) {
        this.siphon = siphon;
    }


    public SiphonResources201ResponseData cargo(@javax.annotation.Nonnull ShipCargo cargo) {
        this.cargo = cargo;
        return this;
    }

    /**
     * Get cargo
     *
     * @return cargo
     */
    @javax.annotation.Nonnull
    public ShipCargo getCargo() {
        return cargo;
    }

    public void setCargo(@javax.annotation.Nonnull ShipCargo cargo) {
        this.cargo = cargo;
    }


    public SiphonResources201ResponseData events(@javax.annotation.Nonnull List<ShipConditionEvent> events) {
        this.events = events;
        return this;
    }

    public SiphonResources201ResponseData addEventsItem(ShipConditionEvent eventsItem) {
        if (this.events == null) {
            this.events = new ArrayList<>();
        }
        this.events.add(eventsItem);
        return this;
    }

    /**
     * Get events
     *
     * @return events
     */
    @javax.annotation.Nonnull
    public List<ShipConditionEvent> getEvents() {
        return events;
    }

    public void setEvents(@javax.annotation.Nonnull List<ShipConditionEvent> events) {
        this.events = events;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SiphonResources201ResponseData siphonResources201ResponseData = (SiphonResources201ResponseData) o;
        return Objects.equals(this.cooldown, siphonResources201ResponseData.cooldown) &&
                Objects.equals(this.siphon, siphonResources201ResponseData.siphon) &&
                Objects.equals(this.cargo, siphonResources201ResponseData.cargo) &&
                Objects.equals(this.events, siphonResources201ResponseData.events);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cooldown, siphon, cargo, events);
    }

    @Override
    public String toString() {
        String sb = "class SiphonResources201ResponseData {\n" +
                "    cooldown: " + toIndentedString(cooldown) + "\n" +
                "    siphon: " + toIndentedString(siphon) + "\n" +
                "    cargo: " + toIndentedString(cargo) + "\n" +
                "    events: " + toIndentedString(events) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("cooldown", "siphon", "cargo", "events"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("cooldown", "siphon", "cargo", "events"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to SiphonResources201ResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!SiphonResources201ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SiphonResources201ResponseData is not found in the empty JSON string", SiphonResources201ResponseData.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!SiphonResources201ResponseData.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SiphonResources201ResponseData` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : SiphonResources201ResponseData.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `cooldown`
        Cooldown.validateJsonElement(jsonObj.get("cooldown"));
        // validate the required field `siphon`
        Siphon.validateJsonElement(jsonObj.get("siphon"));
        // validate the required field `cargo`
        ShipCargo.validateJsonElement(jsonObj.get("cargo"));
        // ensure the json data is an array
        if (!jsonObj.get("events").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `events` to be an array in the JSON string but got `%s`", jsonObj.get("events").toString()));
        }

        JsonArray jsonArrayevents = jsonObj.getAsJsonArray("events");
        // validate the required field `events` (array)
        for (int i = 0; i < jsonArrayevents.size(); i++) {
            ShipConditionEvent.validateJsonElement(jsonArrayevents.get(i));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!SiphonResources201ResponseData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'SiphonResources201ResponseData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SiphonResources201ResponseData> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(SiphonResources201ResponseData.class));

            return (TypeAdapter<T>) new TypeAdapter<SiphonResources201ResponseData>() {
                @Override
                public void write(JsonWriter out, SiphonResources201ResponseData value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public SiphonResources201ResponseData read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of SiphonResources201ResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of SiphonResources201ResponseData
     * @throws IOException if the JSON string is invalid with respect to SiphonResources201ResponseData
     */
    public static SiphonResources201ResponseData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, SiphonResources201ResponseData.class);
    }

    /**
     * Convert an instance of SiphonResources201ResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

