/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import xyz.faria.space.spaceapi.client.JSON;

import java.io.IOException;
import java.util.*;

/**
 * WarpShip200ResponseData
 */
public class WarpShip200ResponseData {
    public static final String SERIALIZED_NAME_FUEL = "fuel";
    @SerializedName(SERIALIZED_NAME_FUEL)
    @javax.annotation.Nonnull
    private ShipFuel fuel;

    public static final String SERIALIZED_NAME_NAV = "nav";
    @SerializedName(SERIALIZED_NAME_NAV)
    @javax.annotation.Nonnull
    private ShipNav nav;

    public WarpShip200ResponseData() {
    }

    public WarpShip200ResponseData fuel(@javax.annotation.Nonnull ShipFuel fuel) {
        this.fuel = fuel;
        return this;
    }

    /**
     * Get fuel
     *
     * @return fuel
     */
    @javax.annotation.Nonnull
    public ShipFuel getFuel() {
        return fuel;
    }

    public void setFuel(@javax.annotation.Nonnull ShipFuel fuel) {
        this.fuel = fuel;
    }


    public WarpShip200ResponseData nav(@javax.annotation.Nonnull ShipNav nav) {
        this.nav = nav;
        return this;
    }

    /**
     * Get nav
     *
     * @return nav
     */
    @javax.annotation.Nonnull
    public ShipNav getNav() {
        return nav;
    }

    public void setNav(@javax.annotation.Nonnull ShipNav nav) {
        this.nav = nav;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WarpShip200ResponseData warpShip200ResponseData = (WarpShip200ResponseData) o;
        return Objects.equals(this.fuel, warpShip200ResponseData.fuel) &&
                Objects.equals(this.nav, warpShip200ResponseData.nav);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fuel, nav);
    }

    @Override
    public String toString() {
        String sb = "class WarpShip200ResponseData {\n" +
                "    fuel: " + toIndentedString(fuel) + "\n" +
                "    nav: " + toIndentedString(nav) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("fuel", "nav"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("fuel", "nav"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to WarpShip200ResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!WarpShip200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WarpShip200ResponseData is not found in the empty JSON string", WarpShip200ResponseData.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!WarpShip200ResponseData.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `WarpShip200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : WarpShip200ResponseData.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `fuel`
        ShipFuel.validateJsonElement(jsonObj.get("fuel"));
        // validate the required field `nav`
        ShipNav.validateJsonElement(jsonObj.get("nav"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!WarpShip200ResponseData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'WarpShip200ResponseData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<WarpShip200ResponseData> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(WarpShip200ResponseData.class));

            return (TypeAdapter<T>) new TypeAdapter<WarpShip200ResponseData>() {
                @Override
                public void write(JsonWriter out, WarpShip200ResponseData value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public WarpShip200ResponseData read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of WarpShip200ResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of WarpShip200ResponseData
     * @throws IOException if the JSON string is invalid with respect to WarpShip200ResponseData
     */
    public static WarpShip200ResponseData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, WarpShip200ResponseData.class);
    }

    /**
     * Convert an instance of WarpShip200ResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

