/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.api;

import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import xyz.faria.space.spaceapi.client.ApiCallback;
import xyz.faria.space.spaceapi.client.ApiClient;
import xyz.faria.space.spaceapi.client.ApiException;
import xyz.faria.space.spaceapi.client.ApiResponse;
import xyz.faria.space.spaceapi.client.Configuration;
import xyz.faria.space.spaceapi.client.Pair;
import xyz.faria.space.spaceapi.model.AcceptContract200Response;
import xyz.faria.space.spaceapi.model.DeliverContract200Response;
import xyz.faria.space.spaceapi.model.DeliverContractRequest;
import xyz.faria.space.spaceapi.model.FulfillContract200Response;
import xyz.faria.space.spaceapi.model.GetContract200Response;
import xyz.faria.space.spaceapi.model.GetContracts200Response;

public class ContractsApi {

    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ContractsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ContractsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for acceptContract
     *
     * @param contractId The contract ID to accept. (required)
     * @param _callback  Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully accepted contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call acceptContractCall(@javax.annotation.Nonnull String contractId,
        final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/my/contracts/{contractId}/accept"
            .replace("{" + "contractId" + "}", localVarApiClient.escapeString(contractId));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call acceptContractValidateBeforeCall(
        @javax.annotation.Nonnull String contractId, final ApiCallback _callback)
        throws ApiException {
        // verify the required parameter 'contractId' is set
        if (contractId == null) {
            throw new ApiException(
                "Missing the required parameter 'contractId' when calling acceptContract(Async)");
        }

        return acceptContractCall(contractId, _callback);

    }

    /**
     * Accept Contract Accept a contract by ID.   You can only accept contracts that were offered to
     * you, were not accepted yet, and whose deadlines has not passed yet.
     *
     * @param contractId The contract ID to accept. (required)
     * @return AcceptContract200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully accepted contract. </td><td>  -  </td></tr>
     * </table>
     */
    public AcceptContract200Response acceptContract(@javax.annotation.Nonnull String contractId)
        throws ApiException {
        ApiResponse<AcceptContract200Response> localVarResp = acceptContractWithHttpInfo(
            contractId);
        return localVarResp.data();
    }

    /**
     * Accept Contract Accept a contract by ID.   You can only accept contracts that were offered to
     * you, were not accepted yet, and whose deadlines has not passed yet.
     *
     * @param contractId The contract ID to accept. (required)
     * @return ApiResponse&lt;AcceptContract200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully accepted contract. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<AcceptContract200Response> acceptContractWithHttpInfo(
        @javax.annotation.Nonnull String contractId) throws ApiException {
        okhttp3.Call localVarCall = acceptContractValidateBeforeCall(contractId, null);
        Type localVarReturnType = new TypeToken<AcceptContract200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Accept Contract (asynchronously) Accept a contract by ID.   You can only accept contracts
     * that were offered to you, were not accepted yet, and whose deadlines has not passed yet.
     *
     * @param contractId The contract ID to accept. (required)
     * @param _callback  The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully accepted contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call acceptContractAsync(@javax.annotation.Nonnull String contractId,
        final ApiCallback<AcceptContract200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = acceptContractValidateBeforeCall(contractId, _callback);
        Type localVarReturnType = new TypeToken<AcceptContract200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for deliverContract
     *
     * @param contractId             The ID of the contract. (required)
     * @param deliverContractRequest (optional)
     * @param _callback              Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully delivered cargo to contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call deliverContractCall(@javax.annotation.Nonnull String contractId,
        @javax.annotation.Nullable DeliverContractRequest deliverContractRequest,
        final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = deliverContractRequest;

        // create path and map variables
        String localVarPath = "/my/contracts/{contractId}/deliver"
            .replace("{" + "contractId" + "}", localVarApiClient.escapeString(contractId));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deliverContractValidateBeforeCall(
        @javax.annotation.Nonnull String contractId,
        @javax.annotation.Nullable DeliverContractRequest deliverContractRequest,
        final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'contractId' is set
        if (contractId == null) {
            throw new ApiException(
                "Missing the required parameter 'contractId' when calling deliverContract(Async)");
        }

        return deliverContractCall(contractId, deliverContractRequest, _callback);

    }

    /**
     * Deliver Cargo to Contract Deliver cargo to a contract.  In order to use this API, a ship must
     * be at the delivery location (denoted in the delivery terms as &#x60;destinationSymbol&#x60;
     * of a contract) and must have a number of units of a good required by this contract in its
     * cargo.  Cargo that was delivered will be removed from the ship&#39;s cargo.
     *
     * @param contractId             The ID of the contract. (required)
     * @param deliverContractRequest (optional)
     * @return DeliverContract200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully delivered cargo to contract. </td><td>  -  </td></tr>
     * </table>
     */
    public DeliverContract200Response deliverContract(@javax.annotation.Nonnull String contractId,
        @javax.annotation.Nullable DeliverContractRequest deliverContractRequest)
        throws ApiException {
        ApiResponse<DeliverContract200Response> localVarResp = deliverContractWithHttpInfo(
            contractId, deliverContractRequest);
        return localVarResp.data();
    }

    /**
     * Deliver Cargo to Contract Deliver cargo to a contract.  In order to use this API, a ship must
     * be at the delivery location (denoted in the delivery terms as &#x60;destinationSymbol&#x60;
     * of a contract) and must have a number of units of a good required by this contract in its
     * cargo.  Cargo that was delivered will be removed from the ship&#39;s cargo.
     *
     * @param contractId             The ID of the contract. (required)
     * @param deliverContractRequest (optional)
     * @return ApiResponse&lt;DeliverContract200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully delivered cargo to contract. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<DeliverContract200Response> deliverContractWithHttpInfo(
        @javax.annotation.Nonnull String contractId,
        @javax.annotation.Nullable DeliverContractRequest deliverContractRequest)
        throws ApiException {
        okhttp3.Call localVarCall = deliverContractValidateBeforeCall(contractId,
            deliverContractRequest, null);
        Type localVarReturnType = new TypeToken<DeliverContract200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Deliver Cargo to Contract (asynchronously) Deliver cargo to a contract.  In order to use this
     * API, a ship must be at the delivery location (denoted in the delivery terms as
     * &#x60;destinationSymbol&#x60; of a contract) and must have a number of units of a good
     * required by this contract in its cargo.  Cargo that was delivered will be removed from the
     * ship&#39;s cargo.
     *
     * @param contractId             The ID of the contract. (required)
     * @param deliverContractRequest (optional)
     * @param _callback              The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully delivered cargo to contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call deliverContractAsync(@javax.annotation.Nonnull String contractId,
        @javax.annotation.Nullable DeliverContractRequest deliverContractRequest,
        final ApiCallback<DeliverContract200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = deliverContractValidateBeforeCall(contractId,
            deliverContractRequest, _callback);
        Type localVarReturnType = new TypeToken<DeliverContract200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for fulfillContract
     *
     * @param contractId The ID of the contract to fulfill. (required)
     * @param _callback  Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fulfilled a contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call fulfillContractCall(@javax.annotation.Nonnull String contractId,
        final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/my/contracts/{contractId}/fulfill"
            .replace("{" + "contractId" + "}", localVarApiClient.escapeString(contractId));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fulfillContractValidateBeforeCall(
        @javax.annotation.Nonnull String contractId, final ApiCallback _callback)
        throws ApiException {
        // verify the required parameter 'contractId' is set
        if (contractId == null) {
            throw new ApiException(
                "Missing the required parameter 'contractId' when calling fulfillContract(Async)");
        }

        return fulfillContractCall(contractId, _callback);

    }

    /**
     * Fulfill Contract Fulfill a contract. Can only be used on contracts that have all of their
     * delivery terms fulfilled.
     *
     * @param contractId The ID of the contract to fulfill. (required)
     * @return FulfillContract200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fulfilled a contract. </td><td>  -  </td></tr>
     * </table>
     */
    public FulfillContract200Response fulfillContract(@javax.annotation.Nonnull String contractId)
        throws ApiException {
        ApiResponse<FulfillContract200Response> localVarResp = fulfillContractWithHttpInfo(
            contractId);
        return localVarResp.data();
    }

    /**
     * Fulfill Contract Fulfill a contract. Can only be used on contracts that have all of their
     * delivery terms fulfilled.
     *
     * @param contractId The ID of the contract to fulfill. (required)
     * @return ApiResponse&lt;FulfillContract200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fulfilled a contract. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<FulfillContract200Response> fulfillContractWithHttpInfo(
        @javax.annotation.Nonnull String contractId) throws ApiException {
        okhttp3.Call localVarCall = fulfillContractValidateBeforeCall(contractId, null);
        Type localVarReturnType = new TypeToken<FulfillContract200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fulfill Contract (asynchronously) Fulfill a contract. Can only be used on contracts that have
     * all of their delivery terms fulfilled.
     *
     * @param contractId The ID of the contract to fulfill. (required)
     * @param _callback  The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fulfilled a contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call fulfillContractAsync(@javax.annotation.Nonnull String contractId,
        final ApiCallback<FulfillContract200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = fulfillContractValidateBeforeCall(contractId, _callback);
        Type localVarReturnType = new TypeToken<FulfillContract200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getContract
     *
     * @param contractId The contract ID (required)
     * @param _callback  Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getContractCall(@javax.annotation.Nonnull String contractId,
        final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/my/contracts/{contractId}"
            .replace("{" + "contractId" + "}", localVarApiClient.escapeString(contractId));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getContractValidateBeforeCall(@javax.annotation.Nonnull String contractId,
        final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'contractId' is set
        if (contractId == null) {
            throw new ApiException(
                "Missing the required parameter 'contractId' when calling getContract(Async)");
        }

        return getContractCall(contractId, _callback);

    }

    /**
     * Get Contract Get the details of a contract by ID.
     *
     * @param contractId The contract ID (required)
     * @return GetContract200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched contract. </td><td>  -  </td></tr>
     * </table>
     */
    public GetContract200Response getContract(@javax.annotation.Nonnull String contractId)
        throws ApiException {
        ApiResponse<GetContract200Response> localVarResp = getContractWithHttpInfo(contractId);
        return localVarResp.data();
    }

    /**
     * Get Contract Get the details of a contract by ID.
     *
     * @param contractId The contract ID (required)
     * @return ApiResponse&lt;GetContract200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched contract. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetContract200Response> getContractWithHttpInfo(
        @javax.annotation.Nonnull String contractId) throws ApiException {
        okhttp3.Call localVarCall = getContractValidateBeforeCall(contractId, null);
        Type localVarReturnType = new TypeToken<GetContract200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Contract (asynchronously) Get the details of a contract by ID.
     *
     * @param contractId The contract ID (required)
     * @param _callback  The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched contract. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getContractAsync(@javax.annotation.Nonnull String contractId,
        final ApiCallback<GetContract200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getContractValidateBeforeCall(contractId, _callback);
        Type localVarReturnType = new TypeToken<GetContract200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getContracts
     *
     * @param page      What entry offset to request (optional, default to 1)
     * @param limit     How many entries to return per page (optional, default to 10)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed contracts. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getContractsCall(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/my/contracts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getContractsValidateBeforeCall(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        return getContractsCall(page, limit, _callback);

    }

    /**
     * List Contracts Return a paginated list of all your contracts.
     *
     * @param page  What entry offset to request (optional, default to 1)
     * @param limit How many entries to return per page (optional, default to 10)
     * @return GetContracts200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed contracts. </td><td>  -  </td></tr>
     * </table>
     */
    public GetContracts200Response getContracts(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<GetContracts200Response> localVarResp = getContractsWithHttpInfo(page, limit);
        return localVarResp.data();
    }

    /**
     * List Contracts Return a paginated list of all your contracts.
     *
     * @param page  What entry offset to request (optional, default to 1)
     * @param limit How many entries to return per page (optional, default to 10)
     * @return ApiResponse&lt;GetContracts200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed contracts. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetContracts200Response> getContractsWithHttpInfo(
        @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit)
        throws ApiException {
        okhttp3.Call localVarCall = getContractsValidateBeforeCall(page, limit, null);
        Type localVarReturnType = new TypeToken<GetContracts200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Contracts (asynchronously) Return a paginated list of all your contracts.
     *
     * @param page      What entry offset to request (optional, default to 1)
     * @param limit     How many entries to return per page (optional, default to 10)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed contracts. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getContractsAsync(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit,
        final ApiCallback<GetContracts200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getContractsValidateBeforeCall(page, limit, _callback);
        Type localVarReturnType = new TypeToken<GetContracts200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
