/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xyz.faria.space.spaceapi.api;

import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import xyz.faria.space.spaceapi.client.ApiCallback;
import xyz.faria.space.spaceapi.client.ApiClient;
import xyz.faria.space.spaceapi.client.ApiException;
import xyz.faria.space.spaceapi.client.ApiResponse;
import xyz.faria.space.spaceapi.client.Configuration;
import xyz.faria.space.spaceapi.client.Pair;
import xyz.faria.space.spaceapi.model.GetConstruction200Response;
import xyz.faria.space.spaceapi.model.GetJumpGate200Response;
import xyz.faria.space.spaceapi.model.GetMarket200Response;
import xyz.faria.space.spaceapi.model.GetShipyard200Response;
import xyz.faria.space.spaceapi.model.GetSystem200Response;
import xyz.faria.space.spaceapi.model.GetSystemWaypoints200Response;
import xyz.faria.space.spaceapi.model.GetSystemWaypointsTraitsParameter;
import xyz.faria.space.spaceapi.model.GetSystems200Response;
import xyz.faria.space.spaceapi.model.GetWaypoint200Response;
import xyz.faria.space.spaceapi.model.SupplyConstruction201Response;
import xyz.faria.space.spaceapi.model.SupplyConstructionRequest;
import xyz.faria.space.spaceapi.model.WaypointType;

public class SystemsApi {

    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SystemsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SystemsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getConstruction
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getConstructionCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol))
            .replace("{" + "waypointSymbol" + "}", localVarApiClient.escapeString(waypointSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getConstructionValidateBeforeCall(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling getConstruction(Async)");
        }

        // verify the required parameter 'waypointSymbol' is set
        if (waypointSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'waypointSymbol' when calling getConstruction(Async)");
        }

        return getConstructionCall(systemSymbol, waypointSymbol, _callback);

    }

    /**
     * Get Construction Site Get construction details for a waypoint. Requires a waypoint with a
     * property of &#x60;isUnderConstruction&#x60; to be true.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return GetConstruction200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public GetConstruction200Response getConstruction(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        ApiResponse<GetConstruction200Response> localVarResp = getConstructionWithHttpInfo(
            systemSymbol, waypointSymbol);
        return localVarResp.data();
    }

    /**
     * Get Construction Site Get construction details for a waypoint. Requires a waypoint with a
     * property of &#x60;isUnderConstruction&#x60; to be true.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return ApiResponse&lt;GetConstruction200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetConstruction200Response> getConstructionWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        okhttp3.Call localVarCall = getConstructionValidateBeforeCall(systemSymbol, waypointSymbol,
            null);
        Type localVarReturnType = new TypeToken<GetConstruction200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Construction Site (asynchronously) Get construction details for a waypoint. Requires a
     * waypoint with a property of &#x60;isUnderConstruction&#x60; to be true.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getConstructionAsync(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        final ApiCallback<GetConstruction200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getConstructionValidateBeforeCall(systemSymbol, waypointSymbol,
            _callback);
        Type localVarReturnType = new TypeToken<GetConstruction200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getJumpGate
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched jump gate. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getJumpGateCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}/waypoints/{waypointSymbol}/jump-gate"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol))
            .replace("{" + "waypointSymbol" + "}", localVarApiClient.escapeString(waypointSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getJumpGateValidateBeforeCall(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling getJumpGate(Async)");
        }

        // verify the required parameter 'waypointSymbol' is set
        if (waypointSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'waypointSymbol' when calling getJumpGate(Async)");
        }

        return getJumpGateCall(systemSymbol, waypointSymbol, _callback);

    }

    /**
     * Get Jump Gate Get jump gate details for a waypoint. Requires a waypoint of type
     * &#x60;JUMP_GATE&#x60; to use.  Waypoints connected to this jump gate can be
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return GetJumpGate200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched jump gate. </td><td>  -  </td></tr>
     * </table>
     */
    public GetJumpGate200Response getJumpGate(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        ApiResponse<GetJumpGate200Response> localVarResp = getJumpGateWithHttpInfo(systemSymbol,
            waypointSymbol);
        return localVarResp.data();
    }

    /**
     * Get Jump Gate Get jump gate details for a waypoint. Requires a waypoint of type
     * &#x60;JUMP_GATE&#x60; to use.  Waypoints connected to this jump gate can be
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return ApiResponse&lt;GetJumpGate200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched jump gate. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetJumpGate200Response> getJumpGateWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        okhttp3.Call localVarCall = getJumpGateValidateBeforeCall(systemSymbol, waypointSymbol,
            null);
        Type localVarReturnType = new TypeToken<GetJumpGate200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Jump Gate (asynchronously) Get jump gate details for a waypoint. Requires a waypoint of
     * type &#x60;JUMP_GATE&#x60; to use.  Waypoints connected to this jump gate can be
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched jump gate. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getJumpGateAsync(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        final ApiCallback<GetJumpGate200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getJumpGateValidateBeforeCall(systemSymbol, waypointSymbol,
            _callback);
        Type localVarReturnType = new TypeToken<GetJumpGate200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getMarket
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the market. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getMarketCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}/waypoints/{waypointSymbol}/market"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol))
            .replace("{" + "waypointSymbol" + "}", localVarApiClient.escapeString(waypointSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMarketValidateBeforeCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling getMarket(Async)");
        }

        // verify the required parameter 'waypointSymbol' is set
        if (waypointSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'waypointSymbol' when calling getMarket(Async)");
        }

        return getMarketCall(systemSymbol, waypointSymbol, _callback);

    }

    /**
     * Get Market Retrieve imports, exports and exchange data from a marketplace. Requires a
     * waypoint that has the &#x60;Marketplace&#x60; trait to use.  Send a ship to the waypoint to
     * access trade good prices and recent transactions. Refer to the [Market Overview
     * page](https://docs.spacetraders.io/game-concepts/markets) to gain better a understanding of
     * the market in the game.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return GetMarket200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the market. </td><td>  -  </td></tr>
     * </table>
     */
    public GetMarket200Response getMarket(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        ApiResponse<GetMarket200Response> localVarResp = getMarketWithHttpInfo(systemSymbol,
            waypointSymbol);
        return localVarResp.data();
    }

    /**
     * Get Market Retrieve imports, exports and exchange data from a marketplace. Requires a
     * waypoint that has the &#x60;Marketplace&#x60; trait to use.  Send a ship to the waypoint to
     * access trade good prices and recent transactions. Refer to the [Market Overview
     * page](https://docs.spacetraders.io/game-concepts/markets) to gain better a understanding of
     * the market in the game.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return ApiResponse&lt;GetMarket200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the market. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetMarket200Response> getMarketWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        okhttp3.Call localVarCall = getMarketValidateBeforeCall(systemSymbol, waypointSymbol, null);
        Type localVarReturnType = new TypeToken<GetMarket200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Market (asynchronously) Retrieve imports, exports and exchange data from a marketplace.
     * Requires a waypoint that has the &#x60;Marketplace&#x60; trait to use.  Send a ship to the
     * waypoint to access trade good prices and recent transactions. Refer to the [Market Overview
     * page](https://docs.spacetraders.io/game-concepts/markets) to gain better a understanding of
     * the market in the game.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the market. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getMarketAsync(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        final ApiCallback<GetMarket200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMarketValidateBeforeCall(systemSymbol, waypointSymbol,
            _callback);
        Type localVarReturnType = new TypeToken<GetMarket200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getShipyard
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the shipyard. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getShipyardCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}/waypoints/{waypointSymbol}/shipyard"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol))
            .replace("{" + "waypointSymbol" + "}", localVarApiClient.escapeString(waypointSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getShipyardValidateBeforeCall(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling getShipyard(Async)");
        }

        // verify the required parameter 'waypointSymbol' is set
        if (waypointSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'waypointSymbol' when calling getShipyard(Async)");
        }

        return getShipyardCall(systemSymbol, waypointSymbol, _callback);

    }

    /**
     * Get Shipyard Get the shipyard for a waypoint. Requires a waypoint that has the
     * &#x60;Shipyard&#x60; trait to use. Send a ship to the waypoint to access data on ships that
     * are currently available for purchase and recent transactions.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return GetShipyard200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the shipyard. </td><td>  -  </td></tr>
     * </table>
     */
    public GetShipyard200Response getShipyard(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        ApiResponse<GetShipyard200Response> localVarResp = getShipyardWithHttpInfo(systemSymbol,
            waypointSymbol);
        return localVarResp.data();
    }

    /**
     * Get Shipyard Get the shipyard for a waypoint. Requires a waypoint that has the
     * &#x60;Shipyard&#x60; trait to use. Send a ship to the waypoint to access data on ships that
     * are currently available for purchase and recent transactions.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return ApiResponse&lt;GetShipyard200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the shipyard. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetShipyard200Response> getShipyardWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        okhttp3.Call localVarCall = getShipyardValidateBeforeCall(systemSymbol, waypointSymbol,
            null);
        Type localVarReturnType = new TypeToken<GetShipyard200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Shipyard (asynchronously) Get the shipyard for a waypoint. Requires a waypoint that has
     * the &#x60;Shipyard&#x60; trait to use. Send a ship to the waypoint to access data on ships
     * that are currently available for purchase and recent transactions.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the shipyard. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getShipyardAsync(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        final ApiCallback<GetShipyard200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getShipyardValidateBeforeCall(systemSymbol, waypointSymbol,
            _callback);
        Type localVarReturnType = new TypeToken<GetShipyard200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getSystem
     *
     * @param systemSymbol The system symbol (required)
     * @param _callback    Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the system. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getSystemCall(@javax.annotation.Nonnull String systemSymbol,
        final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSystemValidateBeforeCall(@javax.annotation.Nonnull String systemSymbol,
        final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling getSystem(Async)");
        }

        return getSystemCall(systemSymbol, _callback);

    }

    /**
     * Get System Get the details of a system.
     *
     * @param systemSymbol The system symbol (required)
     * @return GetSystem200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the system. </td><td>  -  </td></tr>
     * </table>
     */
    public GetSystem200Response getSystem(@javax.annotation.Nonnull String systemSymbol)
        throws ApiException {
        ApiResponse<GetSystem200Response> localVarResp = getSystemWithHttpInfo(systemSymbol);
        return localVarResp.data();
    }

    /**
     * Get System Get the details of a system.
     *
     * @param systemSymbol The system symbol (required)
     * @return ApiResponse&lt;GetSystem200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the system. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetSystem200Response> getSystemWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol) throws ApiException {
        okhttp3.Call localVarCall = getSystemValidateBeforeCall(systemSymbol, null);
        Type localVarReturnType = new TypeToken<GetSystem200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get System (asynchronously) Get the details of a system.
     *
     * @param systemSymbol The system symbol (required)
     * @param _callback    The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched the system. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getSystemAsync(@javax.annotation.Nonnull String systemSymbol,
        final ApiCallback<GetSystem200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSystemValidateBeforeCall(systemSymbol, _callback);
        Type localVarReturnType = new TypeToken<GetSystem200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getSystemWaypoints
     *
     * @param systemSymbol The system symbol (required)
     * @param page         What entry offset to request (optional, default to 1)
     * @param limit        How many entries to return per page (optional, default to 10)
     * @param type         Filter waypoints by type. (optional)
     * @param traits       Filter waypoints by one or more traits. (optional)
     * @param _callback    Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched all waypoints in the system. </td><td>  -
     * </td></tr>
     * </table>
     */
    public okhttp3.Call getSystemWaypointsCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit,
        @javax.annotation.Nullable WaypointType type,
        @javax.annotation.Nullable GetSystemWaypointsTraitsParameter traits,
        final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}/waypoints"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (traits != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("traits", traits));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSystemWaypointsValidateBeforeCall(
        @javax.annotation.Nonnull String systemSymbol, @javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable WaypointType type,
        @javax.annotation.Nullable GetSystemWaypointsTraitsParameter traits,
        final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling getSystemWaypoints(Async)");
        }

        return getSystemWaypointsCall(systemSymbol, page, limit, type, traits, _callback);

    }

    /**
     * List Waypoints in System Return a paginated list of all of the waypoints for a given system.
     * If a waypoint is uncharted, it will return the &#x60;Uncharted&#x60; trait instead of its
     * actual traits.
     *
     * @param systemSymbol The system symbol (required)
     * @param page         What entry offset to request (optional, default to 1)
     * @param limit        How many entries to return per page (optional, default to 10)
     * @param type         Filter waypoints by type. (optional)
     * @param traits       Filter waypoints by one or more traits. (optional)
     * @return GetSystemWaypoints200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched all waypoints in the system. </td><td>  -
     * </td></tr>
     * </table>
     */
    public GetSystemWaypoints200Response getSystemWaypoints(
        @javax.annotation.Nonnull String systemSymbol, @javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable WaypointType type,
        @javax.annotation.Nullable GetSystemWaypointsTraitsParameter traits) throws ApiException {
        ApiResponse<GetSystemWaypoints200Response> localVarResp = getSystemWaypointsWithHttpInfo(
            systemSymbol, page, limit, type, traits);
        return localVarResp.data();
    }

    /**
     * List Waypoints in System Return a paginated list of all of the waypoints for a given system.
     * If a waypoint is uncharted, it will return the &#x60;Uncharted&#x60; trait instead of its
     * actual traits.
     *
     * @param systemSymbol The system symbol (required)
     * @param page         What entry offset to request (optional, default to 1)
     * @param limit        How many entries to return per page (optional, default to 10)
     * @param type         Filter waypoints by type. (optional)
     * @param traits       Filter waypoints by one or more traits. (optional)
     * @return ApiResponse&lt;GetSystemWaypoints200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched all waypoints in the system. </td><td>  -
     * </td></tr>
     * </table>
     */
    public ApiResponse<GetSystemWaypoints200Response> getSystemWaypointsWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol, @javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable WaypointType type,
        @javax.annotation.Nullable GetSystemWaypointsTraitsParameter traits) throws ApiException {
        okhttp3.Call localVarCall = getSystemWaypointsValidateBeforeCall(systemSymbol, page, limit,
            type, traits, null);
        Type localVarReturnType = new TypeToken<GetSystemWaypoints200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Waypoints in System (asynchronously) Return a paginated list of all of the waypoints for
     * a given system.  If a waypoint is uncharted, it will return the &#x60;Uncharted&#x60; trait
     * instead of its actual traits.
     *
     * @param systemSymbol The system symbol (required)
     * @param page         What entry offset to request (optional, default to 1)
     * @param limit        How many entries to return per page (optional, default to 10)
     * @param type         Filter waypoints by type. (optional)
     * @param traits       Filter waypoints by one or more traits. (optional)
     * @param _callback    The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched all waypoints in the system. </td><td>  -
     * </td></tr>
     * </table>
     */
    public okhttp3.Call getSystemWaypointsAsync(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit,
        @javax.annotation.Nullable WaypointType type,
        @javax.annotation.Nullable GetSystemWaypointsTraitsParameter traits,
        final ApiCallback<GetSystemWaypoints200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSystemWaypointsValidateBeforeCall(systemSymbol, page, limit,
            type, traits, _callback);
        Type localVarReturnType = new TypeToken<GetSystemWaypoints200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getSystems
     *
     * @param page      What entry offset to request (optional, default to 1)
     * @param limit     How many entries to return per page (optional, default to 10)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed systems. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getSystemsCall(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSystemsValidateBeforeCall(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        return getSystemsCall(page, limit, _callback);

    }

    /**
     * List Systems Return a paginated list of all systems.
     *
     * @param page  What entry offset to request (optional, default to 1)
     * @param limit How many entries to return per page (optional, default to 10)
     * @return GetSystems200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed systems. </td><td>  -  </td></tr>
     * </table>
     */
    public GetSystems200Response getSystems(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<GetSystems200Response> localVarResp = getSystemsWithHttpInfo(page, limit);
        return localVarResp.data();
    }

    /**
     * List Systems Return a paginated list of all systems.
     *
     * @param page  What entry offset to request (optional, default to 1)
     * @param limit How many entries to return per page (optional, default to 10)
     * @return ApiResponse&lt;GetSystems200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed systems. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetSystems200Response> getSystemsWithHttpInfo(
        @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit)
        throws ApiException {
        okhttp3.Call localVarCall = getSystemsValidateBeforeCall(page, limit, null);
        Type localVarReturnType = new TypeToken<GetSystems200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Systems (asynchronously) Return a paginated list of all systems.
     *
     * @param page      What entry offset to request (optional, default to 1)
     * @param limit     How many entries to return per page (optional, default to 10)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully listed systems. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getSystemsAsync(@javax.annotation.Nullable Integer page,
        @javax.annotation.Nullable Integer limit,
        final ApiCallback<GetSystems200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSystemsValidateBeforeCall(page, limit, _callback);
        Type localVarReturnType = new TypeToken<GetSystems200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getWaypoint
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched waypoint. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getWaypointCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}/waypoints/{waypointSymbol}"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol))
            .replace("{" + "waypointSymbol" + "}", localVarApiClient.escapeString(waypointSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getWaypointValidateBeforeCall(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol, final ApiCallback _callback)
        throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling getWaypoint(Async)");
        }

        // verify the required parameter 'waypointSymbol' is set
        if (waypointSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'waypointSymbol' when calling getWaypoint(Async)");
        }

        return getWaypointCall(systemSymbol, waypointSymbol, _callback);

    }

    /**
     * Get Waypoint View the details of a waypoint.  If the waypoint is uncharted, it will return
     * the &#39;Uncharted&#39; trait instead of its actual traits.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return GetWaypoint200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched waypoint. </td><td>  -  </td></tr>
     * </table>
     */
    public GetWaypoint200Response getWaypoint(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        ApiResponse<GetWaypoint200Response> localVarResp = getWaypointWithHttpInfo(systemSymbol,
            waypointSymbol);
        return localVarResp.data();
    }

    /**
     * Get Waypoint View the details of a waypoint.  If the waypoint is uncharted, it will return
     * the &#39;Uncharted&#39; trait instead of its actual traits.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @return ApiResponse&lt;GetWaypoint200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched waypoint. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<GetWaypoint200Response> getWaypointWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol) throws ApiException {
        okhttp3.Call localVarCall = getWaypointValidateBeforeCall(systemSymbol, waypointSymbol,
            null);
        Type localVarReturnType = new TypeToken<GetWaypoint200Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Waypoint (asynchronously) View the details of a waypoint.  If the waypoint is uncharted,
     * it will return the &#39;Uncharted&#39; trait instead of its actual traits.
     *
     * @param systemSymbol   The system symbol (required)
     * @param waypointSymbol The waypoint symbol (required)
     * @param _callback      The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Successfully fetched waypoint. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getWaypointAsync(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        final ApiCallback<GetWaypoint200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getWaypointValidateBeforeCall(systemSymbol, waypointSymbol,
            _callback);
        Type localVarReturnType = new TypeToken<GetWaypoint200Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for supplyConstruction
     *
     * @param systemSymbol              The system symbol (required)
     * @param waypointSymbol            The waypoint symbol (required)
     * @param supplyConstructionRequest (optional)
     * @param _callback                 Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> Successfully supplied construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call supplyConstructionCall(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        @javax.annotation.Nullable SupplyConstructionRequest supplyConstructionRequest,
        final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[]{};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = supplyConstructionRequest;

        // create path and map variables
        String localVarPath = "/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction/supply"
            .replace("{" + "systemSymbol" + "}", localVarApiClient.escapeString(systemSymbol))
            .replace("{" + "waypointSymbol" + "}", localVarApiClient.escapeString(waypointSymbol));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(
            localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[]{"AgentToken"};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
            localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
            localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call supplyConstructionValidateBeforeCall(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        @javax.annotation.Nullable SupplyConstructionRequest supplyConstructionRequest,
        final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'systemSymbol' is set
        if (systemSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'systemSymbol' when calling supplyConstruction(Async)");
        }

        // verify the required parameter 'waypointSymbol' is set
        if (waypointSymbol == null) {
            throw new ApiException(
                "Missing the required parameter 'waypointSymbol' when calling supplyConstruction(Async)");
        }

        return supplyConstructionCall(systemSymbol, waypointSymbol, supplyConstructionRequest,
            _callback);

    }

    /**
     * Supply Construction Site Supply a construction site with the specified good. Requires a
     * waypoint with a property of &#x60;isUnderConstruction&#x60; to be true.  The good must be in
     * your ship&#39;s cargo. The good will be removed from your ship&#39;s cargo and added to the
     * construction site&#39;s materials.
     *
     * @param systemSymbol              The system symbol (required)
     * @param waypointSymbol            The waypoint symbol (required)
     * @param supplyConstructionRequest (optional)
     * @return SupplyConstruction201Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> Successfully supplied construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public SupplyConstruction201Response supplyConstruction(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        @javax.annotation.Nullable SupplyConstructionRequest supplyConstructionRequest)
        throws ApiException {
        ApiResponse<SupplyConstruction201Response> localVarResp = supplyConstructionWithHttpInfo(
            systemSymbol, waypointSymbol, supplyConstructionRequest);
        return localVarResp.data();
    }

    /**
     * Supply Construction Site Supply a construction site with the specified good. Requires a
     * waypoint with a property of &#x60;isUnderConstruction&#x60; to be true.  The good must be in
     * your ship&#39;s cargo. The good will be removed from your ship&#39;s cargo and added to the
     * construction site&#39;s materials.
     *
     * @param systemSymbol              The system symbol (required)
     * @param waypointSymbol            The waypoint symbol (required)
     * @param supplyConstructionRequest (optional)
     * @return ApiResponse&lt;SupplyConstruction201Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> Successfully supplied construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<SupplyConstruction201Response> supplyConstructionWithHttpInfo(
        @javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        @javax.annotation.Nullable SupplyConstructionRequest supplyConstructionRequest)
        throws ApiException {
        okhttp3.Call localVarCall = supplyConstructionValidateBeforeCall(systemSymbol,
            waypointSymbol, supplyConstructionRequest, null);
        Type localVarReturnType = new TypeToken<SupplyConstruction201Response>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Supply Construction Site (asynchronously) Supply a construction site with the specified good.
     * Requires a waypoint with a property of &#x60;isUnderConstruction&#x60; to be true.  The good
     * must be in your ship&#39;s cargo. The good will be removed from your ship&#39;s cargo and
     * added to the construction site&#39;s materials.
     *
     * @param systemSymbol              The system symbol (required)
     * @param waypointSymbol            The waypoint symbol (required)
     * @param supplyConstructionRequest (optional)
     * @param _callback                 The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> Successfully supplied construction site. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call supplyConstructionAsync(@javax.annotation.Nonnull String systemSymbol,
        @javax.annotation.Nonnull String waypointSymbol,
        @javax.annotation.Nullable SupplyConstructionRequest supplyConstructionRequest,
        final ApiCallback<SupplyConstruction201Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = supplyConstructionValidateBeforeCall(systemSymbol,
            waypointSymbol, supplyConstructionRequest, _callback);
        Type localVarReturnType = new TypeToken<SupplyConstruction201Response>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
